lucyparsons/OpenOversight

- CONTRIB.md
- OpenOversight/app/templates/input_find_officer.html
- OpenOversight/create_db.py
- OpenOversight/test_data.py
This implements #69 to make the test data population a little command line utility: 
```
vagrant@vagrant-ubuntu-trusty-64:/vagrant/OpenOversight$ ./test_data.py --help
usage: test_data.py [-h] [-p] [-c]
optional arguments:
-h, --help      show this help message and exit
-p, --populate  populate the database with test data
-c, --cleanup   delete all test data from the database
vagrant@vagrant-ubuntu-trusty-64:/vagrant/OpenOversight$ ./test_data.py --populate
[*] Populating database with test data...
[*] Completed successfully!
vagrant@vagrant-ubuntu-trusty-64:/vagrant/OpenOversight$ ./test_data.py --cleanup
[*] Cleaning up database...
[*] Completed successfully!
```
> Test data command line utility

- DEPLOY.md
fixes #75 but the line about env variables in `CONTRIB.md` is still what is borked on our deployment. @r4v5 and I can inspect the server but this PR should fix other deployments.
> remove ampersand which throws errors in systemd

- DEPLOY.md
Similar to #75, this fix will pick up the correct variables based on `CONTRIB.md`
> Add PGPASS to systemd environment variable

- .gitignore
- CONTRIB.md
- DEPLOY.md
- OpenOversight/app/__init__.py
- OpenOversight/config.py
- OpenOversight/create_db.py
- OpenOversight/db_repository/README
- OpenOversight/db_repository/manage.py
- OpenOversight/db_repository/migrate.cfg
- Vagrantfile
- requirements.txt
- vagrant/puppet/manifests/default.pp
Ideological discussions about 12-factor apps aside, we currently have
two deployment-specific secrets (DB URI and CSRF token) and we're
assuredly going to add more later. We need a way of managing those that
isn't "creating and managing a new file with secrets" or "stuffing them
in the global environment".
Enter dotenv. This python module lets you specify things in a file
called .env that then get added to the os.environ namespace. This is
handy because instead of deployment requiring hand-hacking of the
process environment, it just lives with the app. It's also a good
starting point if future users of OO don't want to janitor their own
servers: heroku, for instance, mostly works through .env files.
This change did some reworking to the app itself that we should test out
before sending to …
> Switch to using python-dotenv for deployment-specific SECRETS and un-break the test env

- OpenOversight/app/forms.py
- OpenOversight/app/templates/input_find_officer.html
- OpenOversight/app/templates/partials/officer_form_fields_hidden.html
- OpenOversight/app/utils.py
- OpenOversight/tests/test_utils.py
Closes #24 and closes #92 
Also wrote a couple of unit tests to automate the above check.
I noticed that filtering by anything in the assignments table was broken, so I fixed that and made an issue to write some unit tests for pagination (we should do #102 first).
> Implement search by name and badge number

- OpenOversight/app/forms.py
- OpenOversight/app/static/theme.css
- OpenOversight/app/templates/gallery.html
- OpenOversight/app/templates/label_data.html
- OpenOversight/app/templates/partials/roster_form_fields.html
- OpenOversight/app/templates/partials/roster_paginate.html
- OpenOversight/app/templates/tagger_gallery.html
- OpenOversight/app/utils.py
- OpenOversight/app/views.py
This is a new form for volunteers to use to find the OpenOversight ID of the officers in their images. In order to add new tags we need volunteers to figure out which officers are in there. We have people writing down the badge number / name parts that are visible from the photo but once this is deployed they can directly search through the database to find the officer and just give us the OpenOversight ID so we can add the tag. This feature implements step 2 in #106 (master issue for getting new officer images into the database). Closes #111.
> Tagging feature

- fabfile.py
- requirements.txt
initial one line deploy for #38 . A couple of caveats, the staging environment was throwing `out: /bin/bash: /root/.bash_profile: Permission denied` which I don't quite understand. but it works!  If @r4v5 or @scuerda have ideas about making it better, let me know. Also, it has not been tested in prod, only because I assume we only want to deploy dot releases. Is that correct @redshiftzero ? 
```
fab staging deploy
Executing task 'deploy'
run: source /home/nginx/.bashrc
sudo: git pull
out: /bin/bash: /root/.bash_profile: Permission denied
out: From https://github.com/lucyparsons/OpenOversight
out:  + bcf9292...818c0d5 onelinefabric -> origin/onelinefabric  (forced update)
out: Already up-to-date.
out: 
[162.243.156.49] run: sudo systemctl restart openoversight
Done.
```
> Working fabric file

- OpenOversight/app/static/theme.css
Small CSS change to close #98, making the images properly scaled:
> Scale officer images

- OpenOversight/app/templates/gallery.html
Adds explicit links back to the search form at the top of the results page and at the bottom under the query details:
> Add explicit back buttons to top and bottom of gallery page

- OpenOversight/app/templates/input_find_officer.html
On page load: 
On click:
Clicking the "hide" link hides the ranks image again
> Enable hiding of reference ranks with JQuery

- CONTRIB.md
- OpenOversight/run.py
After #136, run.py was in the wrong location, so this PR moves it and updates the developer documentation (in case people are using `run.py` and not `gunicorn` in the dev environment).
> Fix run.py to run dev server

- OpenOversight/app/__init__.py
- OpenOversight/app/main/forms.py
- OpenOversight/app/main/views.py
- OpenOversight/app/templates/403.html
- OpenOversight/app/templates/404.html
- OpenOversight/app/templates/500.html
- OpenOversight/app/templates/complaint.html
- OpenOversight/app/templates/gallery.html
- OpenOversight/app/templates/partials/paginate.html
- OpenOversight/run.py
- OpenOversight/tests/test_routes.py
Make error pages nicer for UX wins:
* Adds GET requests to the /*gallery views since a not-very-user-friendly “Method Not Allowed” error appears when a user refreshes a page (we are correctly POSTing the form values, and after validation we are serving a redirect such that the last request the browser sees is a GET).
* Adds nicely formatted error pages for 404, 403 (needed in advance of the upcoming user accounts branch), and 500 errors.
> Serve nicely formatted error pages

- OpenOversight/app/templates/gallery.html
The placeholder image is working on prod for the `/tagger_gallery`:
However the path is broken for `/gallery`. This commit fixes the placeholder image in the `/gallery` route. @freddymartinez9 go ahead and deploy to staging, if all looks good we can deploy to prod.
> Set placeholder image path in /gallery

- CONTRIB.md
- OpenOversight/app/config.py
Tests were taking a while because we were using a realistic number of officers (if we use all ~15k officers Travis builds time out), so I've made that variable config-specific. We use a realistic number of officers for the development config and a small set of officers for the unit tests and Travis config. 
Also updated the instructions in `CONTRIB.md` to instruct people how to use `pytest` as the unit test runner.
> Speed up unit tests

- OpenOversight/app/templates/partials/paginate.html
- OpenOversight/app/templates/partials/roster_paginate.html
Use bootstrap icons for pagination navigation
Before:
After:
> Prettify pagination

- OpenOversight/app/config.py
- OpenOversight/app/main/forms.py
- OpenOversight/app/main/views.py
- OpenOversight/app/templates/base.html
- OpenOversight/app/templates/index.html
- OpenOversight/app/templates/submit.html
- OpenOversight/app/utils.py
- OpenOversight/tests/conftest.py
- OpenOversight/tests/test_routes.py
- OpenOversight/tests/test_utils.py
- dev-requirements.txt
- requirements.txt
- test_data.py
This PR closes issue #5, to implement in-app photo uploads to S3. 
Submission route `/submit` is now available to logged in users of the application:
Anonymous users will continue to use the Google Drive submission. However, once #90 (sanitize images (both to handle potentially malicious uploads and to remove metadata)) and #148 (privacy-respecting captcha on this form) are implemented then we can remove the login required decorator from this view and deprecate the Google drive submission form. 
Details:
* Uploads are limited in size and in file type (to images).
* Images are uploaded first to `/tmp` and then to the S3 bucket for OpenOversight. We should eventually have the S3 upload and deletion of the file from `/tmp` be a celery task. The first part (saving to `/tmp`) is quite fast
* A …
> Photo submissions to S3

- DOCKER_DEPLOY.md
- Dockerfile
This Dockerfile can be used for a containerized deployment with Kubernetes or similar platforms. It doesn't currently do any database setup, but DOCKER_DEPLOY.md provides instructions on how to do this manually.
> Add basic Dockerfile for the webapp

- OpenOversight/app/templates/sort.html
Forgot to modify the buttons on `/sort` to be POST only during #169. Definitely need to write functional tests to catch stuff like this (appended to my ever increasing to do list)
> State-changing routes on /sort are POST only

- OpenOversight/tests/test_routes.py
Updates unit tests for user registration to:
* use a strong password in the user registration with legit credentials unit test
* add a unit test to verify that users with a weak password cannot register
> Update unit tests for user registration

- OpenOversight/app/main/views.py
- OpenOversight/tests/test_routes.py
A user trying to insert duplicate tags can run into an IntegrityError:
```
IntegrityError: (psycopg2.IntegrityError) duplicate key value violates unique constraint 
"unique_faces"
DETAIL:  Key (officer_id, img_id)=(2, 1) already exists.
```
This PR adds exception handling for this situation, by rolling back the database transaction and flashing a message to the user letting them know the tag already exists (so they can try again):
This PR also adds a unit test for the case when a user tries to insert a duplicate tag.
> Add exception handling for when a user tries to insert duplicate tags

- OpenOversight/app/__init__.py
- OpenOversight/app/main/views.py
- OpenOversight/manage.py
Implements #186:
* Logs error when a exception occurs uploading an officer image to S3 (also I've verified that the photo upload does work in the development environment with a test S3 bucket). 
* Logs info event when an administrator account is created.
> Add logging of application events and errors

- CONTRIB.md
- OpenOversight/app/db_repository/versions/002_migration.py
- OpenOversight/app/models.py
- OpenOversight/manage.py
Fixes #194, where the filepath in the images table was too small. 
Also, in the course of making this change, I ran into a situation where the automatically generated migrations by `sqlalchemy-migrate` did not work, and instead I had to [manually write the migrations](https://sqlalchemy-migrate.readthedocs.io/en/v0.7.1/changeset.html). To make it easier for developers in the future, I've modified `manage.py` a bit (this workflow will seem familiar to Django people):
* First, a developer will run `python manage.py makemigrations` in order to have `sqlalchemy-migrate` attempt to automatically generate the migrations. 
* Then, a developer will inspect and edit them (if necessary) and _then_ will run `python manage.py migrate` to actually apply the migrations. 
For deploying to staging and …
> Fix filepath field length

- fabfile.py
This was tested on staging:
```
27 ganglia openoversight % fab staging migrate
[staging.openoversight.lucyparsonslabs.com] Executing task 'migrate'
Apply any outstanding database migrations? [y/N] y
[staging.openoversight.lucyparsonslabs.com] run: su nginx -c "/home/nginx/oovirtenv/venv/bin/python OpenOversight/manage.py migrate"
[staging.openoversight.lucyparsonslabs.com] out: --------------------------------------------------------------------------------
[staging.openoversight.lucyparsonslabs.com] out: INFO in __init__ [/home/nginx/oovirtenv/venv/OpenOversight/OpenOversight/app/__init__.py:52]:
[staging.openoversight.lucyparsonslabs.com] out: OpenOversight startup
[staging.openoversight.lucyparsonslabs.com] out: --------------------------------------------------------------------------- …
```
> Update the fabfile to run migrations

- OpenOversight/app/main/views.py
- OpenOversight/tests/conftest.py
On the tagging route, rolling back transactions was causing errors as the User object was no longer bound to a session. This was causing a test failure. I've refactored this to avoid doing a rollback by testing if the row exists first. It is not a very [EAFP](https://docs.python.org/2/glossary.html?highlight=eafp#term-eafp) solution but... it is a working one where tests pass. So for now we can keep it like this.
> Refactor tagging route

- OpenOversight/app/utils.py
Naive fix for the following stacktrace, seen when viewing /sort route on staging:
```
2017-03-03 04:15:04 [5053] [ERROR] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 126, in handle_request
respiter = self.wsgi(environ, resp.start_response)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2000, in __call__
return self.wsgi_app(environ, start_response)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1991, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1567, in handle_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in …
```
> Remove reference to non-global variable

- OpenOversight/app/__init__.py
- requirements.txt
Closes #154.
- Adds Flask-Limiter
- Sets up rate limiting using an in-memory store (100/min, 5/sec)
Need to install the new addition to requirements.txt. That should be it!
> Rate limit requests

- OpenOversight/app/main/views.py
- OpenOversight/app/templates/cop_face.html
- OpenOversight/app/templates/sort.html
- OpenOversight/app/utils.py
This resolves another annoyance I've noticed while testing the 0.2 release. Changes proposed in this pull request:
- The image shown on the classification and identification apps is now random: if you go there again, a random different image will be shown.
- You can also now click the new skip button to skip over an image you are having trouble with (this doesn't remove it from the queue and you may be shown the same image later).
> Add skip buttons to classification and identification apps

- OpenOversight/app/templates/cop_face.html
- OpenOversight/app/templates/image.html
- OpenOversight/app/templates/tag.html
These are some changes to the volunteer tagging workflow for the 0.2 release (x-link #174). 
- Enable the addition of tags on the `/cop_face/<image_id>` route (previously you would have to label the first image returned from querying all untagged images in order).
- Add button to the `/tag` and `/image` routes to enable admins to quickly enter the cop identification app for a particular image.
Nothing special needed
> Improvements to cop identification workflow

- OpenOversight/app/main/views.py
- OpenOversight/app/templates/officer.html
- OpenOversight/app/templates/tagger_gallery.html
- OpenOversight/tests/test_routes.py
Closes #160 and resolves #212.
- Adds officer profiles. A new route `officer/<officer_id>` exists for each officer. This route displays all the info we have on them: assignment history, demographic data, face.
- The profile shows all known badge numbers for the officer.
- Adds a link to these profiles in the tagger gallery.
> Create officer profiles

- OpenOversight/app/templates/gallery.html
- OpenOversight/app/templates/profile.html
- OpenOversight/app/templates/tag.html
- OpenOversight/app/templates/tagger_gallery.html
Closes #177.
- Show only the face (not the full image) on the tag and gallery routes.
- Add links to officer profiles on the user profile, main gallery, and tag route. 
> Generate face bounding box cutouts of submitted images

- OpenOversight/app/templates/submit.html
Resolves #196.
- Adds a note to the submission page that SecureDrop is a great way to get us videos or images for the high security context. I don't want to encourage it too much since it's annoying af for us, but I think it's important that it's there just in case.
> Add notice that users should use SecureDrop for high security submissions

- OpenOversight/app/config.py
- OpenOversight/app/main/views.py
- OpenOversight/app/static/css/dropzone.css
- OpenOversight/app/static/js/dropzone.js
- OpenOversight/app/templates/submit.html
- OpenOversight/app/utils.py
- OpenOversight/tests/test_routes.py
- OpenOversight/tests/test_utils.py
Closes #150.
- Adds support for multiple file uploads on the `/submit` route using [Dropzone.js](http://www.dropzonejs.com/)
- You can now drag and drop up to 50 files into the submission box and upload them at once
- Thumbnails will now appear (generated client-side)
- If a file fails to upload, a circular X icon appears over the image and a red tooltip appears on hover with the reason: "File type not allowed!", "Image already uploaded to OpenOversight!", "Server error encountered. Try again later." (e.g. issue with S3)
> Implement multiple file uploads and drag and drop uploads

- OpenOversight/app/__init__.py
- OpenOversight/app/main/views.py
- OpenOversight/app/templates/429.html
- OpenOversight/app/templates/base.html
- OpenOversight/tests/test_routes.py
Closes #148.
- Deprecates Google form in favor of uploading directly to the application (and remove login requirement for /submit)
- Adds stricter rate limiting on the submit page only
- Adds error handler for 429 too many requests
> Rate limit uploads, add custom 429 error handler

- OpenOversight/app/main/forms.py
- OpenOversight/app/main/views.py
- OpenOversight/app/models.py
- OpenOversight/app/templates/base.html
- OpenOversight/app/templates/officer.html
- OpenOversight/app/utils.py
- OpenOversight/tests/conftest.py
- OpenOversight/tests/test_models.py
- OpenOversight/tests/test_routes.py
- OpenOversight/tests/test_utils.py
- test_data.py
Resolves #214.
- Adds a admin-only panel on the officer profile enabling an administrator to add a new assignment (and badge number, rank and unit) for an officer. An admin might do this when we get an updated roster, or when officers send us their updated data when they get promoted (this actually did happen). 
> Enable admins to add assignments for officers

- OpenOversight/app/templates/base.html
- OpenOversight/app/templates/sort.html
- OpenOversight/app/templates/tag.html
- OpenOversight/app/templates/tagger_gallery.html
Noticed a few wonky things testing on staging today that I've fixed in this PR:
- Link to "Skip picture" on classification app sent people to the wrong volunteer app.
- "Try again" link on tagger search results went back to the volunteer homepage. Now it goes back to the tagger officer search form. 
- If the cutouts of the tag were really large (we have some high res photos, we can see cop's pores) then they overflowed the box which was ugly.
> Fixes from 0.2 QA round 1

- OpenOversight/app/main/views.py
- OpenOversight/app/templates/officer.html
OK the logging I just merged in revealed the error on the staging server: some of the officers in the real database don't have photos, so `face` was None.
> Fix officer profile bug

- DEPLOY.md
- fabfile.py
DEPLOY.md (and, coincidentally, OO in staging and prod) asserts the
existence of a virtualenv but doesn't actually manage it very well. So,
for instance, the `pip install` command in `fabfile.py` installs
`requirements.txt`, but for some reason has a good chance of doing it in
the system python context. Which is not ideal, to say the least, because
user `nginx` can't write to `/usr` to populate these, and people who
think they've deployed a new dep may see the deployed service fail to
start. This change makes the virtualenv usage a little more explicit:
we're spawning a gunicorn installed and managed by the virtualenv, and
we're running the pip/python explicitly from the venv.
Also, the backup dumped the sql twice and gave it a name that
didn't sort lexicographically. This fixes that. …
> Make the fabfile backup and deploy better

- OpenOversight/app/templates/profile.html
- OpenOversight/tests/test_routes.py
- Adds a user's email to the profile page only for administrators. This way we can email users.
- Adds tests to check that we see the email if we are an admin but not if we are a regular user.
> Add a user's email to the profile page

- OpenOversight/app/auth/views.py
- OpenOversight/tests/test_routes.py
Fixes #259
Fixes #259: 'Redundant phrasing: "email has been sent to you by email"'
[x] pytests pass in the development environment on my local machine **except for the ones that already fail in develop**
> ...email has been sent to you{ by email,}

- README.md
README.md: Added local vagrant dev account credentials
- README.md: Added local vagrant dev account credentials
> README.md: Added local vagrant dev account credentials

- OpenOversight/app/templates/auth/login.html
- OpenOversight/app/templates/auth/register.html
Fixes #263 
- Changed login form to custom form (was `wtf.quick_form(form, ...)`) to prep for next change
- Login and register forms now autofocus on their first form field
> Added autofocus to first input field of login, registration forms

- OpenOversight/app/templates/leaderboard.html
Fixes #273
Fixes #273 
- Fixed leaderboard (users + scores were all on the same line)
> leaderboard.html: Added line breaks between user scores

- OpenOversight/app/utils.py
- OpenOversight/tests/test_utils.py
- vagrant/puppet/manifests/default.pp
Fixes an issue reported on our Slack where files with capitalized extensions were incorrectly rejected by the backend.
Also updates the version of gecko-webdriver installed by the puppet provisioner, since the previous was old enough to 404.
> Accept case insensitive filenames for uploads

- OpenOversight/app/db_repository/versions/003_migration.py
- OpenOversight/app/main/forms.py
- OpenOversight/app/main/views.py
- OpenOversight/app/models.py
- OpenOversight/app/templates/add_department.html
- OpenOversight/app/templates/base.html
- OpenOversight/app/templates/departments.html
- OpenOversight/tests/conftest.py
- OpenOversight/tests/test_models.py
- OpenOversight/tests/test_routes.py
- Vagrantfile
- test_data.py
This PR adds first steps towards initial multi-department support (partially #296):
* Adds a 'departments' model to enable the web application to store which police departments the instance of OpenOversight supports. 
* Adds a new page (`/departments`) to list and manage basic data about each new police department. We can extend this to store the ranks for each department and any other department-specific information.
* Adds a new admin-only form to add a new department (`/department/new`)
1. After this is deployed, I will go into the admin panel and add "Chicago Police Department" as the first department. 
2. In a followup PR I will further decouple the code from Chicago (e.g. once step 1 is done then I can remove the hardcoded "Chicago Police Department" from all …
> Initial multi department support

- OpenOversight/app/db_repository/versions/004_migration.py
- OpenOversight/app/main/views.py
- OpenOversight/app/models.py
- OpenOversight/app/templates/submit_department.html
- OpenOversight/app/templates/submit_deptselect.html
- OpenOversight/manage.py
- OpenOversight/tests/conftest.py
- OpenOversight/tests/test_routes.py
- test_data.py
This PR extends initial multi-department support:
* Links existing images to the first department (Chicago in the case of LPL's instance). 
* Adds a first step in the photo submission flow for the user to indicate _which department_ the photos are for. 
1. Checkout base PR:
```
git checkout multi-dept-submission
```
2. Provision development VM, and migrate the database: 
```
vagrant up
vagrant ssh
source ~/oovirtenv/bin/activate
cd /vagrant/OpenOversight
python manage.py migrate
```
No errors should appear.
3. Link existing images to the first department:
```
python manage.py link_images_to_department 
```
If you want to verify that images are linked to the right department, you can always do the following in `python manage.py shell`:
```
>>> from app.models import Image …
```
> Add multi-department support for photo submission

- vagrant/puppet/manifests/default.pp
Gunicorn fails to start up on first vagrant provision because it cannot
write to /tmp/openoversight.log, because gunicorn starts up as www-data
instead of the vagrant user:
```python
root@vagrant-ubuntu-trusty-64:~# cat /etc/gunicorn.d/oo
CONFIG = {
'mode': 'wsgi',
'environment': {
'PYTHONPATH': '/home/vagrant/oovirtenv'
},
'working_dir': '/vagrant/OpenOversight',
'user': 'www-data',
'group': 'www-data',
'python': '/home/vagrant/oovirtenv/bin/python',
'args': (
'--bind=0.0.0.0:3000',
'--workers=3',
'--timeout=30',
'--log-level=error',
'app:app',
),
}
```
As specced, it doesn't look like there's a hard-coded knob for user/group
gunicorn runs as: https://github.com/stankevich/puppet-python#pythongunicorn
So we can either change the template (ew) or change the permissions on …
> Fix vagrant provisioning to let gunicorn write oo logs (#299)

- OpenOversight/app/db_repository/versions/005_migration.py
- OpenOversight/app/models.py
- OpenOversight/app/templates/image.html
- OpenOversight/app/templates/tag.html
- OpenOversight/manage.py
Fixes #305.
- Adds foreign key constraint (and migration) between images and departments tables
- Shows the police department on the image page:
> Show police department on the image and tag detail pages

- .travis.yml
- test_data.py
Fixes #317. 
- The department must exist prior to the images being created
because the image is foreign keyed to the police departments.
- I guess `flake8` got updated because it's failing on E722, so ignoring that for now in the interest of keeping these bits moving
None, test data and CI only
-  [x] `flake8` checks pass
> Fix development VM

- OpenOversight/app/main/views.py
- OpenOversight/app/templates/label_data.html
- OpenOversight/app/templates/sort.html
- OpenOversight/tests/test_routes.py
Fixes #309, enables volunteers to classify images from a particular police department
Straightforward, no migrations needed
> Add multi department volunteer image classification support

- OpenOversight/app/static/css/openoversight.css
- OpenOversight/app/templates/about.html
- OpenOversight/app/templates/base.html
- OpenOversight/app/templates/index.html
- OpenOversight/app/templates/input_find_officer.html
- OpenOversight/app/templates/label_data.html
- OpenOversight/app/templates/submit_deptselect.html
Ready for review- frontend work continued; styling changes only // no copy changes
Could definitely use design feedback on the about page if people have opinions!
Adds on to #332 .
Also kinda touches on #292 ? could add in a little icon or something too if securedrop should be called out more
- Redesign of 'about' page
- Adds footer content
- Minor adjustments to 'find' and 'volunteer' pages
- Responsive fix for homepage header
- Minor styling changes to nav
About + footer additions: 
Volunteer:
Find an officer:
> 322 revamp cont

- OpenOversight/app/main/forms.py
- OpenOversight/app/main/views.py
- OpenOversight/app/templates/edit_assignment.html
- OpenOversight/app/templates/officer.html
- OpenOversight/app/utils.py
- OpenOversight/tests/test_routes.py
Fixes #337.
easy pease
Adds a wee pencil icon next to each officer assignment which takes one to a form to update the relevant fields:
> Enable admins to edit assignments data

- OpenOversight/app/main/forms.py
- OpenOversight/app/main/views.py
- OpenOversight/app/templates/edit_officer.html
- OpenOversight/app/templates/officer.html
- OpenOversight/app/utils.py
- OpenOversight/tests/test_routes.py
- requirements.txt
Fixes #330 
Nothin' fancy
Adds a wee pencil edit button next to table of officer info on their profile which takes the person to a officer edit form:
> Enable admins to edit existing officer information

- OpenOversight/app/main/forms.py
- OpenOversight/app/templates/gallery.html
- OpenOversight/app/templates/index.html
- OpenOversight/app/templates/input_find_officer.html
- OpenOversight/app/templates/label_data.html
- OpenOversight/app/utils.py
- OpenOversight/tests/conftest.py
- OpenOversight/tests/test_functional.py
- OpenOversight/tests/test_routes.py
- OpenOversight/tests/test_utils.py
Closes #308. Closes #344.
- Removes hardcoded "CPD" and "Chicago Police Department"
- Enables people to search by department:
Nothing fancy here
> Complete multi department support

- OpenOversight/app/utils.py
- OpenOversight/tests/test_utils.py
@bmintz pointed out in #290 that we don't set content-type on the images we upload to S3, leading to some frustrating browser experiences.
This naively sets them based on file extension, with the assumption that browsers will figure it out if someone uploads, say, a .png with a .gif extension.
It also adds a test to make sure that any added ALLOWED_EXTENSIONS are handled properly in `guess_mime_type()` to make sure we have programmatic prompting to keep the list up to date.
I don't actually know how deep inside the s3 library call we want to go to add a test asserting that a mock of the call has mime-type set, so I punted on that.
This doesn't fix historical S3 uploads, unfortunately, which I'll have to do by manually (well, programmatically, but outside of OO) re-PUTing them.
Tested that …
> Set content-type on uploaded images

- OpenOversight/app/main/forms.py
Hello,
To reference on issues #345 i've set the field rank "PO" by default when you add a New Officer in Volunteer page, if you can tell me if it's good or not :)
> Officer template should default to PO

- vagrant/puppet/manifests/default.pp
- This PR fixes the issue reported by @pierwill and @magpiewings in #366 in the development environment. The issue was (from Slack):
"when i run `python manage.py db migrate` per `CONTRIB.md` i get
```(oovirtenv)vagrant@vagrant-ubuntu-trusty-64:/vagrant/OpenOversight$ python manage.py db migrate
--------------------------------------------------------------------------------
INFO in __init__ [/vagrant/OpenOversight/app/__init__.py:57]:
OpenOversight startup
--------------------------------------------------------------------------------
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
Traceback (most recent call last):
File "manage.py", line 94, in …
```
> Fix migrations in vagrant dev env

- OpenOversight/app/main/views.py
- OpenOversight/app/templates/base.html
- OpenOversight/app/templates/browse.html
- OpenOversight/app/templates/gallery.html
- OpenOversight/app/templates/index.html
- OpenOversight/app/templates/label_data.html
- OpenOversight/app/templates/list_officer.html
- OpenOversight/app/templates/partials/officer_name.html
- OpenOversight/tests/test_routes.py
Fixes #327 .
- Creates a list view for departments
- When searches yield no results, users are redirected to the list view so they can look through all the officers
- Does not have complete testing, the tests in #422 need to be in working order and then can include these tests.
> 327 list view

- OpenOversight/app/main/views.py
The route handler raises an error if it receives an empty string as the
department id. This ensures that if there is no department id, we are
still redirected correctly.
Fixes an error introduced when fixing tagging in #430 
- Change the redirect after tagging a photo to send user to accommodate the situation in which a department is not set.
-[ x ] I have rebased my changes on current `develop`
-[ x ] pytests pass in the development environment on my local machine
-[ x ] `flake8` checks pass
> Do not use department id if there is none.

- OpenOversight/app/static/css/dropzone-override.css
- OpenOversight/app/templates/submit_department.html
- OpenOversight/app/templates/submit_deptselect.html
Overrides dropzone's checkmark animation
Puts links to stylesheets in the header on dropzone pages
Fixes 373.
- Overrides the default css animation to an animation that stays put.
[x ] I have rebased my changes on current `develop`
[ x] pytests pass in the development environment on my local machine
[ x] `flake8` checks pass
> Success checkmark stays after file upload

- OpenOversight/app/main/forms.py
- OpenOversight/tests/routes/test_incidents.py
Fixes #442
- Adds validation such that incidents <1900 cannot be made:
> Fix year validation on incident form

- OpenOversight/app/utils.py
- OpenOversight/tests/conftest.py
- OpenOversight/tests/test_utils.py
- test_data.py
Fixes #425
- For some departments, we do not have per-officer race or gender information. In those cases, we do not currently return them if a user searches for a specific gender. This is confusing behavior - for a query for all male officers, we should return all male officers and those we are not sure about. Longer term, area coordinators should be maintaining this information  if possible.
No db migrations
> Filter by race, gender: Return officers that we do not have race, gender info for

- OpenOversight/app/main/model_view.py
- OpenOversight/app/main/views.py
- OpenOversight/app/templates/officer.html
- OpenOversight/tests/routes/test_incidents.py
Fixes #455 .
- Changes the url on the officer page to include the officer id
- Changes how the model view handles urls
- Prepopulates incident form with officer ID when coming from the officer's page.
> Prepopulate officer ID on incident form

- OpenOversight/app/main/forms.py
- OpenOversight/app/templates/incident_detail.html
- OpenOversight/app/templates/incident_list.html
Fixes #456 .
- Removes the required from the incident report number field in the incident form
- Makes the appropriate changes to the templates to deal with non-numbered incidents
> Do not require a report number to create an incident

- OpenOversight/app/static/js/incidentAddButtons.js
Fixes #457 
The last link/license plate is now hidden rather than removed
Inputs on the form are cleared when it is hidden
This allows us to preserve the csrf token so that the form will send correctly
**To Review**
Go to the create a new incident page.
Add a license plate, remove it. Verify that the incident is created correctly and the license plate you made is not in it.
Do the same for links.
> Hide last formset instead of removing it

- OpenOversight/app/utils.py
- OpenOversight/tests/test_utils.py
Fixes #440 .
- use a left join on Assignment
- Added a test to be sure it worked
> Include officers without assignments in search results

- CONTRIB.md
- DEPLOY.md
- PULL_REQUEST_TEMPLATE.md
- README.md
Create links between documentation files + a few other small changes
- Create links between documentation files.
- Add requests to read to the code of conduct in both README and CONTRIB.
- Fix inconsequential typo in a link in README.
- Add note that PR template should populate automatically.
- Make checkboxes in PR template actual checkboxes.
- N/A ~pytests pass in the development environment on my local machine~
- N/A ~`flake8` checks pass~
> Create links between documentation files

- OpenOversight/app/utils.py
- OpenOversight/tests/test_utils.py
Fixes #483
- This will prevent sadness for others configuring S3 in the development environment, or others that are spinning up this project on their own infra
- On staging, we should test photo uploads (I did test this in a dev env with valid S3 creds)
> Get URL of object uploaded to S3 from S3

- .travis.yml
- create_db.py
- flickrscraper/resize.and.detect.py
- socmint/grab_socmint.py
- test_data.py
The request to run `flake8` can be confusing: there are no linting errors reported in CI (as it's run from the OpenOversight directory). But in the root of the repo, there are a few linting errors. 
- Resolve the remainder of flake8 linting issues in the root of the repo
- Run linting in CI from the root of the repo to prevent issues going forward
> Resolve all flake8 issues in root of repo

- Makefile
Previously, the default Makefile target listed `clean` before `test` and `stop`. This would cause an error when running the default target with `make` because it would try to remove running containers:
```
$ make
make build
docker-compose build postgres
...
docker rm openoversight_web_1
Error response from daemon: You cannot remove a running container e20158d3fee56fb8908a85731d64391c3a4ad5f12d83ae6ca4d03cf168695574. Stop the container before attempting removal or force remove
make: *** [clean] Error 1
```
I put `clean` at the end of the default target list, which resolved the error and allowed all the targets to run successfully:
```
$ make
make build
docker-compose build postgres
...
======================================================== 217 passed in 170.06 seconds …
```
> Switch default order of Make targets

- OpenOversight/app/formfields.py
- OpenOversight/app/main/forms.py
- OpenOversight/app/models.py
- OpenOversight/app/templates/partials/incident_fields.html
Fixes #505
- Quick fix to show which fields are optional in incident form
- (and a few more fields will be optional)
- (want to get this in #508)
> Incident form: show which fields are optional

- OpenOversight/app/templates/officer.html
quick fix, link formatted poorly (see this ICE agent's profile: https://openoversight.com/officer/24840)
deploying to staging to test
> Quick fix for link in wrong place on profile

- OpenOversight/app/main/forms.py
- OpenOversight/tests/routes/test_incidents.py
Fixes #519.
The drop-down for selecting the state in the add incident form has an empty value as its default. Since the field is required, leaving the field on this value shouldn't be allowed.
Similarly if a license plate number is added, the state field cannot be left untouched.
- Adding a boolean flag to the `allowed_values` function so that it is possible to exclude the empty string as an allowed value, so that not changing the license plate raises a validation flag
- For the license plate, I added a validator to the form `LicensePlateForm` which doesn't allow the number field to be filled, but the state field be empty.
This is my first pull request ever, so looking forward to any feedback.
I didn't find any tests …
> fixing #519

- CONTRIB.md
- OpenOversight/manage.py
- README.md
- Vagrantfile
- docker-compose.yml
- vagrant/puppet/manifests/default.pp
Currently the management interface (manage.py) won't interact with the Docker dev environment when run from localhost, since it requires direct database access. 
* Moves the Postgres port to standard 5432 and exposes it to the host
* Removes the `runserver` command from manage.py since running it would cause a port conflict with the already running instance in Docker. The `runserver` command is still available as it is a default command in Flask-Script and runs on port 5000.
* Updates the CONTRIB documentation to reflect the changes. Now all management commands should work with the Docker env when run from localhost, including database migrations.
> Use management interface with Docker dev environment

- OpenOversight/app/templates/partials/paginate_nav.html
- OpenOversight/tests/test_functional.py
Displays "Showing (x)-(y) of (total)" between Next and Prev buttons when browsing officer listings
Fixes #501 
- display "Showing (x)-(y) of (total)"  in paginate_nav.html
- new test in test_functional.py
-
> Show user position in pagination when browsing

- OpenOversight/app/main/forms.py
- OpenOversight/app/main/views.py
- OpenOversight/app/static/js/incidentAddButtons.js
- OpenOversight/app/templates/partials/incident_form.html
- OpenOversight/app/utils.py
- OpenOversight/tests/routes/test_incidents.py
Fixes #443 .
- Allow extra officers to be removed from the incident form
- Change remove button action to remove any element in any position
> Remove extra officers from incidents

- OpenOversight/app/main/forms.py
- OpenOversight/app/main/views.py
- OpenOversight/app/templates/add_edit_department.html
- OpenOversight/app/templates/browse.html
- OpenOversight/tests/routes/test_officer_and_department.py
Fixes #306  .
- Admins see an edit-button in '/browse' now (see screenshot)
- Clicking the button leads to an edit-form very similar to the form for adding a new department
- Changes to the department name and short-name can be made
I am reusing the template (which I renamed to add_edit_department.html)  and form for adding a department since the two forms are very similar (except for the title and submit button being named "Update" instead of "Add") and to reduce copy and pasting of code. I hope this is acceptable.
> 306 department editable

- OpenOversight/app/templates/list_officer.html
- OpenOversight/app/templates/partials/officer_name.html
Fixes issue displaying officers with a race value of NULL.
Properly display middle names that are not initials (in Baltimore some middle names are given as initials and some as full middle names).
Fix rank display in officer list (they were previously all showing up as Unknown).
> Fixes for officer name and profile display

- OpenOversight/app/main/views.py
Avoid displaying of departments without officers
Fixes issue #491 .
- Only get departments with officers
> Do not return Departments with no officers

- docker-compose.yml
- requirements.txt
Fixes CVE-2018-1000164 in gunicorn. Don't know if we're explicitly vulnerable, but let's not dawdle finding out. I propose cherry-picking this into master and releasing it as soon as it successfully deploys to staging, @redshiftzero.
- upgrade gunicorn from 17.5 to 19.9 (latest as of this moment)
- add the gunicorn 19+ specific '--reload' flag for development environment
- I haven't done one of these in long enough to know if `pip install requirements.txt` over the existing gunicorn installation makes it inaccessible, and if so, for how long.
> Upgrade gunicorn to fix a CVE, and get live reloading in dev for free

- OpenOversight/app/templates/base.html
Fixes #496 .
- Change the bootstrap columns in the footer from `col-lg-4` to `col-sm-4`.  The footer will still collapse, but only when the screen is much smaller.  See screenshots below for comparison.
- Footer with `col-sm-4` doesn't collapse when the website takes up half the desktop (Screenshot 1).
-  <img width="1680" alt="screen shot 2018-09-02 at 12 06 22 pm" src="https://user-images.githubusercontent.com/5529982/44958689-55621f00-aea9-11e8-9876-6cc5c3bf3fd7.png">
-   It does collapse when the website is smaller (Screenshot 2).
- <img width="1680" alt="screen shot 2018-09-02 at 12 06 34 pm" src="https://user-images.githubusercontent.com/5529982/44958692-5dba5a00-aea9-11e8-91af-27b38d278e00.png">
- Footer with `col-lg-4` …
> tweak footer template to use smaller columns

- README.md
- Make the documentation be `pip install -r dev-requirements.txt` instead of `pip install dev-requirements.txt` because `pip install dev-requirements.txt` didn't work
One pytest didn't pass, `test_admins_can_edit_incident_links_and_licenses`, but it was already failing before I made this change.
> tweak documentation for installing dependencies

- dev-requirements.txt
- In #553, @McEileen reported issues with a test failure and `flake8`, to ensure that we are all on the same development dependencies, this PR pins them to specific versions
Development env only
> Pin development dependencies

- README.md
- docs/area_coordinator.rst
- docs/index.rst
- I've set up our docs to be autobuilt on commit to `master` or `develop` on ReadTheDocs, you can see it here: https://openoversight.readthedocs.io/en/latest/
- I've added the beginning of an area coordinator guide to the `docs/` directory here so potential documentation contributors have an example and starting point
> Add ReadTheDocs build, beginnings of area coordinator guide

- OpenOversight/app/main/model_view.py
In the model view edit form, where the `creator_id` is set on the form, the check for whether or not the object has one attempts to set `form.creator_id.data = obj.creator_id` *only* if `obj.creator_id` returned None, which then prevented setting the current user's id instead. This prevented editing incidents, so I fixed the if statement to work as the comment above that line describes.
> fix bug preventing incident edit form submission

- .dockerignore
Fixes  an error where `make build` would crash.
```
postgres uses an image, skipping                                                                          
Building web                                                                                              
Traceback (most recent call last):                                                                        
File "bin/docker-compose", line 6, in <module>                                                          
File "compose/cli/main.py", line 71, in main                                                            
File "compose/cli/main.py", line 127, in perform_command                                                
File "compose/cli/main.py", line 287, in build …
```
> avoid trying to push container_data to dockerd

- OpenOversight/app/__init__.py
- OpenOversight/app/templates/officer.html
Fixes #569 
Added a template filter to calculate age based on birth year, and updated the officer profile to include the age alongside the birth year in parenthesis e.g., `1955 (63)`.
> include age next to birth year in officer profile

- OpenOversight/app/templates/officer.html
- OpenOversight/tests/test_functional.py
Fixes #582 
- Navigation Breadcrumbs for Office Page
Nuns.
> Navigation Breadcrumb For Officer Page

- .travis.yml
- OpenOversight/app/__init__.py
- OpenOversight/app/auth/views.py
- OpenOversight/app/models.py
- OpenOversight/app/utils.py
- OpenOversight/db_backup.py
- OpenOversight/manage.py
- OpenOversight/tests/routes/route_helpers.py
- OpenOversight/tests/routes/test_auth.py
- OpenOversight/tests/routes/test_descriptions.py
- OpenOversight/tests/routes/test_image_tagging.py
- OpenOversight/tests/routes/test_incidents.py
- OpenOversight/tests/routes/test_notes.py
- OpenOversight/tests/routes/test_officer_and_department.py
- OpenOversight/tests/routes/test_other.py
- OpenOversight/tests/routes/test_user_api.py
- OpenOversight/tests/test_functional.py
- OpenOversight/tests/test_utils.py
- dockerfiles/web/Dockerfile
- flickrscraper/flickrgroup.py
- flickrscraper/readme.md
- flickrscraper/resize.and.detect.py
- requirements.txt
- test_data.py
in progress
Adds python3 support, builds a python3 development environment instead of python2.
- python3 support
- change relative import to explicit relative import (see [the docs](https://docs.python.org/3/tutorial/modules.html#intra-package-references) for more info)
- urlparse got absorbed into urllib.parse in python3, so conditionally import it from the new place but fall back to the python2 place
- fixups in manage.py and backup_db.py
- change path in test data to a non-relative path so images display (in production these are AWS URLs so this shouldn't be an issue, but they were 404ing from /department and /officer/<id>)
- don't, yet, at all
> First pass at python3 support

- .travis.yml
- Makefile
- dev-requirements.txt
- Tests were starting to get a bit slow, so they are now run by multiple workers and distributed one test file per worker such that the selenium tests don't need to be modified (they fail if run in parallel as is)
> Parallelize tests: 100s speedup

- OpenOversight/app/templates/sort.html
- OpenOversight/tests/routes/test_image_tagging.py
Simply changes the wording on the sort page to ask "Is there a *Uniformed* officer in this photo?" I myself was confused by the original wording the first time I clicked "volunteer" on OO.
None
N/A
> Improve wording on sort page

- CONTRIB.md
- OpenOversight/app/__init__.py
- OpenOversight/app/commands.py
- OpenOversight/migrations/env.py
- OpenOversight/migrations/versions/59e9993c169c_change_faces_to_thumbnails.py
- requirements.txt
This simply migrates the management commands from Flask-Script to Flask's built-in CLI.
Instead of:
`python manage.py make_admin_user`
you can now do:
`flask make-admin-user`
> Switch from Flask-Script to built-in Flask CLI

- OpenOversight/app/config.py
These changes will cause OO to get additional email settings and the CSRF secret key from environment variables if available, but keeping the same default values.
To test, add `MAIL_SERVER`, `OO_MAIL_SUBJECT_PREFIX`, `OO_MAIL_SENDER` to `.env` and perform an action that sends an email (like user account registration).
> Email settings pulled from environment vars if available

- OpenOversight/app/main/views.py
- OpenOversight/app/templates/submit_image.html
- OpenOversight/tests/test_models.py
Fixes #376 .
- If the user is logged in, their user ID will be added to the raw_images table along with the image information
- A note has been added on the photo submission page asking logged out users to sign up and log in. For logged in users, a note is added that their user ID will be attached to their photo submission.
> Log who submitted photo

- Makefile
- docker-compose.yml
Commit f850c0f44262617c9f101b257951b208f61b7869 added the `FLASK_ENV` environment variable to the docker web service. Because it is set to `development`, pytest will fail when run within docker, such as when you run `make test`.
This fix pulls FLASK_ENV from the host environment so that `make test` will run without error.
> Pull FLASK_ENV from host environment so tests will run in docker

- OpenOversight/migrations/versions/2a9064a2507c_remove_dots_middle_initial.py
- OpenOversight/migrations/versions/5c5b80cab45e_add_approved.py
Migration script to remove "." and "-" entries for middle initial of officers.
Fixes #580 
- Quick migration script that removes entries that only have a dot "." or a dash "-"
- I haven't done a migration script before. But it did what it's supposed to be doing on my version
- I followed what's done in 59e9993c169c_change_faces_to_thumbnails.py for the import of app.models, not sure if a more "database-centric" (without using the model) approach is preferred.
> Fixing #580

- requirements.txt
(Fixing this because it's causing confusion for new contributors, supercedes #618)
Previously we were getting a warning about the fact that the built
wheel packages for psycopg2 are to be distributed under another name,
psycopg2-binary. These wheels are recommended [in the docs](http://initd.org/psycopg/docs/install.html#binary-install-from-pypi
) not for
production use. Let's keep what we have now and suppress the warning via specifying
--no-binary in the requirements file (also see the psycopg2 issue comment [here](https://github.com/psycopg/psycopg2/issues/674#issuecomment-434352029)).
> requirements: specify to install psycopg2 from source

- OpenOversight/app/commands.py
This fixes some minor issues with the `bulk-add-officers` command that I ran into when importing Baltimore data, mostly relating to matching against blank strings.
> Fixes to bulk_add_officers

- OpenOversight/app/main/views.py
Fixes exception handling as in 3123aa2
> Remove errant format_exc param in views

- OpenOversight/app/models.py
Ready for review. Big thanks to @McEileen for helping to troubleshoot this!
This fixes a weird bug we were seeing that seemed to only occur in Linux environments. As far as I can tell, the generated tokens used in the user registration system were being deserialized as bytes rather than strings in some environments, causing 3 tests to fail. This fixes that by ensuring generated tokens are deserialized and decoded into utf-8 strings.
> Decode generated tokens to fix environment-specific bug

- OpenOversight/tests/conftest.py
- OpenOversight/tests/routes/route_helpers.py
- OpenOversight/tests/test_functional.py
- README.md
Fixes #649.
- Remove from `README.md` log-in credentials that didn't work 
I didn't run pytests because I only changed documentation.
I didn't run `flake8` because I only changed documentation.
> remove out of date test credentials

- CONTRIB.md
Fixes #638  .
- Add explanation of how to use pdb with both tests and the app itself.
I didn't run pytests because I only changed documentation.
I didn't run `flake8` because I only changed documentation.
> add documentation about pdb

- OpenOversight/app/templates/officer.html
Tiny change that only shows overtime pay on officer profiles when it's greater than zero. For some of the officer salary data I have, they have a higher annual salary than their total annual pay, and IMO it doesn't really make sense to display a negative overtime amount.
Before:
After:
> Only display overtime pay if it is greater than zero

- OpenOversight/tests/test_alembic.py
This is a test to guard against branching migrations history (see: https://github.com/lucyparsons/OpenOversight/pull/671). We _could_ force the rebase of all PRs on the very latest `develop` prior to merge so that this test will prevent the merge of any branching migrations (without that, even with this test it's still possible that branching migrations will land in `develop` if a PR's CI run occurred on an out-of-date `develop`), but that will produce even more slowdown to merge. With this test we'll at least be alerted in `develop` (and more likely prior to merge) by failing the `develop` build, at which time we can address and fix. 
Test only
> test: add test for branching database migration history

- fabfile.py
First pass, so we can at least get deploying unblocked.
Two things I'd like to add later:
* make sure we're on a appropriate branch with a clean workdir
* wipe out remote static/dist/ dir before scping new files
But this will suffice to unblock deploys. Still requiring python2
fabric, unfortunately. Sloppily fixes #658.
Fixes #658.
- Makes it possible again
> Locally build and ship assets to remote servers

- .circleci/config.yml
- .travis.yml
I'm mostly adding this because I turned on Circle CI building for the CD
pipeline in PR #685 and I don't want our CI checks to have a red build indicator
until that PR is merged, so this PR moves linting checks from Travis into a separate CI job
> ci: add separate lint job

- .circleci/config.yml
- .travis.yml
- fabfile.py
- requirements.txt
The idea here is to:
- Back up staging and deploy the latest state of `develop` upon merge of a PR into `develop`
- Back up production and deploy the latest state of `master` upon merge of a PR into `master`
Also closes #118 by adding a weekly backup (in case no merges to master happen in a week)
1. Merge this PR
2. Observe deploy
While working on this PR I had the staging deployment workflow triggered on PR, you can see the successful workflow here: https://circleci.com/gh/lucyparsons/OpenOversight/49 (noting this such that you can prove to yourself this actually works). I've removed this now that it's ready for merge.
Maintainers will need to:
1. Observe Slack, watch for any deploy failures from the "OpenOversight CI/CD" integration I added and act upon them to resolve …
> CD pipeline for automated backup and deployment to staging and production

- .circleci/config.yml
Fixes CD (was breaking because some dependencies (libpq-dev) weren't installing due to Trusty, which is EOL) and updates to Ubuntu Xenial (surprisingly the default machine executor is still Trusty in Circle CI!): https://circleci.com/gh/lucyparsons/OpenOversight/59
> cd: use ubuntu xenial for backup and deployment jobs

- requirements.txt
Fixes https://github.com/lucyparsons/OpenOversight/issues/699
Just bumps the Flask-WTF according to @redshiftzero's suggestion in https://github.com/lucyparsons/OpenOversight/issues/699.
- Bump Flask-WTF from 0.14.2 to 0.14.3 (the latest version at the time of writing).
None.
These don't pass either, but it's nothing I changed on this PR.
> Bump Flask-WTF version.

- OpenOversight/tests/conftest.py
- test_data.py
The function mockdata() in conftest.py apparently needs to be decorated
as a pytest fixture in order for unit tests to work. However, the test
data population scripts call mockdata() directly, which leads to an
error saying pytest fixures cannot be called directly. This fix
undecorated mockdata(), renames it to add_mockdata(), and adds a
new, decorated mockdata() function which wraps add_mockdata(). Test data
script work now, and tests pass.
Fixes https://github.com/lucyparsons/OpenOversight/issues/701.
- See description, above.
None that I know of
> Add an undecorated version of the mockdata func

- OpenOversight/app/config.py
Fixes https://github.com/lucyparsons/OpenOversight/issues/709.
- Allow users to upload files ending in ".jpe". This is important because a popular social media site hosts JPEG files with this extension.
> Allow uploading files with the ".jpe" extension

- OpenOversight/app/templates/partials/paginate_nav.html
Ready for review.
Previously, when no results were returned for a search, the page navigation text output was confusing.  It would display something like "Showing 1 of 0" pages, and this text appeared twice.  This PR makes the text read "Showing 0 of 0" pages, and removes the duplicate text.
- Page navigation text reads "Showing 0 of 0" instead of "Showing 1 of 0"
- When zero results are returned for a search, the "Showing 0 of 0" text is printed only once
Old output when search returns no results:
New output when search returns no results:
- [x ] I have rebased my changes on current `develop`
> Modify pager output when search returns no results

- Makefile
- docker-compose.yml
- dockerfiles/web/Dockerfile
Fixes #713 
- Moves the dev postgres storage to a docker volume, which removes a lot of the difficulties of managing file permissions shared between the docker container and the host. 
- Sets the web container to run as the same UID as the current user.  That does a couple of things
- Makes the `__pycache__` directories that get created on the host's filesystem owned by the user, which makes them manageable and deleteable from outside the container.
- Gives the container process access to the OpenOversight/app/static/dist directory so that css compilation works like you expect, without needing fancy `sudo` tricks.
- This will invalidate any dev database you currently have.  We're no longer looking at …
> Docker compose local file permissions

- OpenOversight/app/static/css/openoversight.css
- OpenOversight/app/templates/cop_face.html
in progress
Explanatory text is now displayed on mouseover of buttons for officer identification.
- [ x] I have rebased my changes on current `develop`
> Explanatory text displayed on button mouseover.

- OpenOversight/app/templates/about.html
- OpenOversight/app/templates/cop_face.html
- OpenOversight/app/templates/index.html
- OpenOversight/app/templates/input_find_ooid.html
- OpenOversight/app/templates/label_data.html
- OpenOversight/app/templates/submit_image.html
- OpenOversight/app/templates/submit_officer_image.html
- OpenOversight/app/templates/tutorial.html
- README.md
This modifies OpenOversight to instruct folks to submit _any_ photos of officers - as long as they are in uniform. We will request that clear faces are in the frame. It will be preferred for badge numbers and/or name tags to also be in frame, but no longer strictly required. 
This will enable us to better handle the following cases: (i) where area coordinators know all cops in the city and can identify officers by face alone, (ii) where officers are in public with their badge covered by tape and there already are other images of that same face in the database.
Initially I was thinking there should be two volunteer "cop identification" buckets for folks to work from, one for identifying cops by badge/name, and one for identifying cops by face, but I'm thinking now that …
> allow photo submission with only faces, no longer require badges/names in frame

- .circleci/config.yml
Closes #724
openoversight.com prod is deploying from `main` (done as of 0.5.2)
This CI config takes effect for the prod branch when we next merge from `develop` -> `main`, so this PR just ensures that the branch names in the CI config are updated.
> rename prod branch from master to main

- Makefile
- docker-compose.yml
In #714 we created a reliance on an environment variable called DC_UID to import the user id into docker-compose. The Makefile populates that variable automatically, but for folks that invoke docker-compose directly, that variable wasn't getting set with frustrating results (root-owned files that couldn't be used or deleted).
This PR removes that custom variable and uses the shell-default UID variable.  That is able to be set by the Makefile, and appears to be the most common variable name for this function in docker-compose.  See https://github.com/docker/compose/issues/2380 where folks have been fighting this for at least 5 years now.  If for whatever reason docker-compose is started with a UID in the environment, it now errors …
> Make the docker-compose reliance on UID explicit

- OpenOversight/app/main/views.py
- OpenOversight/app/models.py
- OpenOversight/app/templates/all_depts.html
- OpenOversight/tests/routes/test_officer_and_department.py
Wanting to work with the CPD data I noticed that some of the data I would like to get is not included in the csv-file generated in the "Download department data" files. Looking into it, I also noticed that instead of the python csv library a "home-grown" solution is used.
- Deprecating the existing officer-csv download (not removing in case there are any scripts directly accessing the page)
- Adding a new officer-csv download that uses the python csv library and is therefore more robust (can deal with "," in strings for example)
- Adding the unique internal identifier to the csv output
- Replacing the assignments field with providing the (most recent) badge number and job title of each officer
- Adding a field most recent salary to …
> new officers csv download - added assignments csv download

- OpenOversight/app/utils.py
- OpenOversight/tests/routes/test_officer_and_department.py
Fixes #744.
- Refactor the `add_officer_profile` method, called by the `add_officer()` method in `views.py`, so that it won't break when the new officer's unit is included
- Test the bug fix
n/a
I didn't include screenshots, because I didn't change the display.
> debug add officer form and test unit feature

- OpenOversight/app/templates/submit_image.html
- OpenOversight/app/templates/submit_officer_image.html
A lot of the text on the [submit page](https://openoversight.com/submit) is super teeny (and I would say not great for accessibility), both due to a missing slash in a `</small>` tag, and the `small` class being applied to paragraph tags. This PR addresses both of those, making the text less teeny and more readable.
> Make teeny text less teeny

- docker-compose.yml
This is related to https://github.com/lucyparsons/OpenOversight/pull/739, which turned out to be an incomplete solution. This fixes an issue whereby, if the user tries to run docker-compose by hand (outside of the Makefile), they would run into an error:
```
int10h@maxwell ~/projects/OpenOversight $ docker-compose run --rm web flask bulk-add-officers --help
WARNING: The AWS_ACCESS_KEY_ID variable is not set. Defaulting to a blank string.
WARNING: The AWS_SECRET_ACCESS_KEY variable is not set. Defaulting to a blank string.
WARNING: The AWS_DEFAULT_REGION variable is not set. Defaulting to a blank string.
WARNING: The S3_BUCKET_NAME variable is not set. Defaulting to a blank string.
WARNING: The APPROVE_REGISTRATIONS variable is not set. Defaulting to a blank string.
ERROR: …
```
> Fix leftover issues w/ $UID

- OpenOversight/app/main/views.py
- OpenOversight/tests/routes/test_officer_and_department.py
Fixes #708.
- Previously, if a user deleted a rank through the department edit page, the change didn't persist.
- This fix makes the change persist.
- As of Thursday, June 4, this was the last bug I knew of on staging!
I made [a video ](https://www.dropbox.com/s/uzpp06hjyno3qcm/OORankFix.mp4?dl=0)of the functionality.
> persist deleting rank on department edit page

- .travis.yml
- docker-compose.yml
- dockerfiles/web/Dockerfile
There's a regression in python 3.8.4, which broke all 3 of our builds despite the travis build matrix. This is because we weren't actually running the tests using those versions, because the tests run inside docker where the version was specified by the Dockerfile to be 3.8.
Luckily, flake8 was still running in the travis python version, so we caught things like f-strings not being supported in 3.5.
I expect this will fail on 3.8 and pass on 3.5, 3.6, and 3.7, but I won't know until it's pushed. Once that's verified to work, we can drop 3.8 support until we're running an OS somewhere that needs it or the image is fixed.
Fixes #754 .
> Test the python versions we think we're testing

- OpenOversight/app/auth/views.py
Fixes #762 .
- Add a condition to the auth method `before_request()`, so that it doesn't err out when request.endpoint is `None`
> handle auth check for when request.endpoint is None

- .gitignore
- .travis.yml
- OpenOversight/migrations/versions/114919b27a9f_.py
- dev-requirements.txt
- flickrscraper/resize.and.detect.py
- requirements.txt
In looking at flask-sqlalchemy's github issue about the underlying issue from #754 / #758, I realized that:
a) they already pushed a fixed release of flask-sqlalchemy
b) this will affect anyone who happens to be running a 3.8.4, which
shouldn't be too many people, but may be nonzero
Let's just add the fixed package, just in case. And while I'm here, let's test against 3.8 again too.
> Upgrade Flask-SQLAlchemy to guard against #754

- OpenOversight/app/__init__.py
- OpenOversight/app/auth/views.py
- OpenOversight/app/config.py
- OpenOversight/app/main/views.py
- requirements.txt
This autogenerates a sitemap at `/sitemap.xml`. If there are more than 10,000 items, it will produce a sitemap index and paginated sitemaps. This will help search engines like Google when they crawl the site.
To test, `make dev`, then visit http://localhost:3000/sitemap.xml
> Use Flask-Sitemap to autogenerate an XML sitemap

- .circleci/config.yml
temporarily disabling production backup in CD until we address the issue in #740 (once this is merged we can merge `develop` into `main`)
> temp: disable automated production backup

- OpenOversight/app/email.py
- OpenOversight/app/models.py
The previous code path was missing a `commit()` in the db session that marked users as confirmed when accessing the /auth/confirm/<token> route, so add that.
Also, to make local testing of email not require a full SMTP server running, we can just log the email contents if our flask app environment is not production or staging.
Fixes #762 (in my local testing, at least).
> Confirm the confirmed users, allow fake email for devs

- dockerfiles/web/Dockerfile
- package.json
Docker was complaining about the version of nodejs we were running just because it stopped being supported in December. Upgrade to latest nodejs 12 LTS.
Also, upgrade the version of node-sass we use to a version compatible with nodejs 12.
No visible differences in our generated CSS, though I did not do a before/after CSS diff.
> Upgrade to latest NodeJS LTS

- OpenOversight/app/email.py
I got greedy and removed the access to the protected
_get_current_object() without understanding why it was there in the
first place.
Fixes this stacktrace:
Exception in thread Thread-21:
Traceback (most recent call last):
File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
self.run()
File "/usr/lib/python3.5/threading.py", line 862, in run
self._target(*self._args, **self._kwargs)
File "/home/nginx/oovirtenv/venv/OpenOversight/OpenOversight/app/email.py", line 8, in send_async_email
with app.app_context():
File "/home/nginx/oovirtenv/venv/lib/python3.5/site-packages/werkzeug/local.py", line 347, in __getattr__
return getattr(self._get_current_object(), name)
File "/home/nginx/oovirtenv/venv/lib/python3.5/site-packages/werkzeug/local.py", line 306, in _get_current_object …
> Fix activation emails, this time for sure

- OpenOversight/app/templates/list_officer.html
Fixes #793.
CPD's browse page threw a 500 on prod and staging because in the below line in `list_officer.html`,
```
{% set star_no = "#" + assignment.star_no %}
```
`assignment` was `none`.  I initially thought this was because assignments were missing from the database for CPD.  However, when I deleted all assignments for a department on my local instance, I wasn't able to reproduce the error.  Also, I realize that the below line
```
{% if officer.assignments.all() %}
````
should prevent the template from attempting to set `star_no` when an officer has no assignments.
I think the error occurs when the below line 
```
{% set assignment = officer.assignments.order_by(officer.assignments[0].__table__.c.star_date.desc()).first() %}
```
sets assignment to equal `none`.  I …
> ensure that star_no doesn't 500 if assignment sort returns None

- db_backup.py
- fabfile.py
Fixes #799.
Re-enabling the db-backup functionality by moving the script into the root dir and changing the fab-file that calls the script.
This should allow us to use absolute imports again.
I am not familiar with the circleci + fab stuff and don't know how to test it. So I was only able to test running the script itself, which worked.
> fixing #799

- OpenOversight/app/commands.py
- OpenOversight/app/csv_imports.py
- OpenOversight/app/model_imports.py
Fixes staging
- Fixing staging by changing absolute imports to relative imports
I tested the changes by exec'ing into the running web-container and running `gunicorn -w 4 -b 127.0.0.1:4000 app:app` which seems to be the command used on staging/production according to https://github.com/lucyparsons/OpenOversight/blob/develop/DEPLOY.md and the command failed before the changes similarly to the staging error message.
> relative imports to fix staging

- OpenOversight/tests/routes/test_image_tagging.py
This fixes an error in the `test_featured_tag_replaces_others()` test. The mocked `crop_image()` function wasn't returning the image that was actually being used to create the tag.
> Fix for test_featured_tag_replaces_others()

- OpenOversight/app/main/forms.py
Fixes #818  .
- Change SelectField to StringField since the SelectField has no `choice` set which breaks the form-validation in wtforms `2.2.1` the version that is running on staging.
- I observed that the field is still displayed as a html select element in the search-officer form.
- I tested the change by adding a requirement for wtforms 2.2.1 locally and reproducing the error on staging. The error disappeared with the proposed change
> Change SelectField to StringField

- OpenOversight/app/main/views.py
- OpenOversight/tests/test_functional.py
Fixes #814.
- Set race to 'Not Sure' in edit officer form when officer has NULL value for race (was previously defaulting to 'Black')
- Set gender to 'Not Sure' in edit officer form when officer has NULL value for gender (was previously defaulting to 'Male')
- DRY up the admin login routines for functional tests
First, set race and gender to `NULL` for an officer in `psql`:
------
Then, load the edit officer form and see 'Not Sure' is now the default value for race and gender:
------
```
% git rebase develop
Current branch 814-not-sure-race-and-gender-defaults is up to date.
```
```
360 passed, 20 warnings in 363.65s (0:06:03)
```
```
docker-compose run --rm web flake8
Starting openoversight_postgres_1 ... done
reidparham@Reids-MBP …
```
> 814: ensure NULL race or gender in edit officer form are coerced to 'Not Sure'

- OpenOversight/app/main/views.py
- OpenOversight/app/models.py
- OpenOversight/app/utils.py
- OpenOversight/tests/test_functional.py
Fixes #810.
- Alpha sort `Unit` within models, forms, utils, and views
- Test the sorting
This looks like the 'correct' sort order:
------
```
360 passed, 20 warnings in 356.49s (0:05:56)
```
> 810: alpha sort the options for 'Unit' select

- OpenOversight/app/main/views.py
Fixes #827.
- Change 'order by' criteria for search results from (last name) to (last name, first name, id). (last name) doesn't uniquely identify officers, so the order by clause doesn't give a deterministic row sequence, breaking pagination. (last name, first name, id) fixes the issue by uniquely identifies officers.
> 827: fix pagination/change ordering criteria for search results

- OpenOversight/app/templates/cop_face.html
- OpenOversight/app/templates/tutorial.html
Related to #237, but does not complete that issue. These changes aim to ensure users understand the gravity and permanence of triggering `main.complete_tagging` for a photo. I’ve seen users thinking it only dismisses that photo from _their individual_ identification queue.
- Improve **text** of two buttons
- Improve **explanation** for one button
```
% git rebase develop
Current branch 237-improve-identification-ui is up to date.
```
```
359 passed, 19 warnings in 331.29s (0:05:31)
```
```
% flake8 --ignore=E501,E722,W504,W503
% echo $?
0
```
> 237: improve identification UI

- OpenOversight/app/utils.py
I ran into what might be an edge case, where `imghdr.what()` failed to figure out the filetype of a submitted photo. So I added in this little snippet in case imghdr fails, to determine image type using the filename.
I'm not really sure what a good way to add tests for this is, since I don't really know why `imghdr` failed for this particular image. For reference, the image was https://bpdwatch.s3.amazonaws.com/8d/095b8184d1d4abd90e867a8b2d41961bcc4fbd2b42e2af6f0ad8c80ca44fc7.jpg
> When imghdr fails to deduce the image type, use file extension

- OpenOversight/app/commands.py
- OpenOversight/app/utils.py
I realized some of the logic I originally wrote in the `update_officer_from_row()` function of the `bulk-add-officers` command didn't make any sense. I removed the `allowed_blank` parameter since there isn't a situation where you would _update_ an officer field to be blank if it wasn't already. Plus the way it was written caused an issue when I was importing the latest roster CSV for bpdwatch.com: the middle initial column was blank for many officers and subsequently importing the CSV blanked out the middle initials in the database for many officers that had existing non-null middle initials. Not today, Satan!
This also updates the command to prompt the user to confirm the proposed changes _before_ committing them to the database, allowing you to actually review that long …
> Prompt before committing with bulk-add-officers command

- OpenOversight/app/templates/submit_image.html
add 'image/webp' to acceptedFiles for Dropzone, so the front-end part of the file upload page allows `*.webp` images.
Fixes #844 .
> Quick follow up on #845

- .circleci/config.yml
I _think_ this is broken because we attempt to do the backup in an image
that doesn't have pyenv but just has python 3.6.
@redshiftzero is there a way to test this config.yml before it gets to the main branch? I can't see anywhere in circleci that would make it possible.
Fixes #740 maybe? or at least moves it closer to happening.
> Use ubuntu image for backup script

- OpenOversight/app/templates/sort.html
Fixes an issue where the link from the image classification page when there are no more images to classify, like https://openoversight.com/sort/department/7 to the image tagging is not forwarding the selected department. The expectation (at least for me) is that after finishing classifying the images  submitted for one department a user expects to tag the images for the department they just classified not for all departments.
> fix link from image sorting to image tagging

- OpenOversight/migrations/versions/cd39b33b5360_constrain_officer_gender_options.py
Staging still uses postgres 9.2 and therefore doesn't support the `citext` module.
This PR will replace the use of `citext` by the `LOWER` function which is sufficient for our purpose here.
> change migration to use LOWER not citext

- OpenOversight/app/config.py
- OpenOversight/app/main/views.py
- OpenOversight/app/models.py
- OpenOversight/app/templates/list_officer.html
- OpenOversight/app/templates/tagger_gallery.html
- OpenOversight/app/utils.py
- OpenOversight/tests/routes/test_officer_and_department.py
- OpenOversight/tests/test_utils.py
Fixes #857.
- Rewriting parts of `filter_by_form`. The SQL queried emitted by the current form leads to inefficient results and produces a lot of queries
- This will load all assignments for all selected officers in one query via a SELECT IN query (https://docs.sqlalchemy.org/en/14/orm/loading_relationships.html#selectin-eager-loading)
- Setting `SQLALCHEMY_ECHO = True` for the development environment to make it easier for people to see the generated SQL code. Might be a little verbose
This should be tested thoroughly on staging, since the changes potentially touch a lot of different views and functionality
> simplify and streamline officer filtering

- DEPLOY.md
This PR updates the CORS configuration in the deployment instructions to use JSON rather than XML. When I tried setting this up myself, AWS would only accept JSON in the CORS configuration field.
> Update deployment docs to use JSON for CORS policy

- .github/workflows/main.yml
- OpenOversight/app/config.py
Set up github actions to replace the dependency on travis. They recently changed their model and it is no longer free for open source projects.
Additionally I made a change on how the config is selected so that the `FLASK_ENV = testing` is actually honored.
This will also require changing the settings on the branch protection to work correctly.
I tested this on my fork https://github.com/abandoned-prototype/OpenOversight/actions
> Set up GitHub action

- OpenOversight/app/main/views.py
- OpenOversight/app/utils.py
Fixes two bugs in officer search:
1. Pagination currently depends on officer assignments instead of distinct officers. That is, each page has 20 historical assignments instead of 20 cops.
2. Featured tags aren't shown in officer search.
- Modify the officer query in the filter_by_form function to only pull distinct officers
- Reverse sorting of officer images so the 0th index is the feature tag
> Fix two small bugs in officer search

- dockerfiles/web/Dockerfile
Add checksum verifications for two dependencies downloaded in a Dockerfile. I've computed the hashes locally using `sha256sum`. They will have to be recomputed when updated. This also pulls the node setup script from version control to avoid breaking the verification if the upstream version is updated.
Looks like Mozilla actually does [publish](https://github.com/mozilla/geckodriver/releases) cryptographic signatures for gecko releases. We can use the checksum method in this PR for simplicity, or I'm happy to update this to use the signature.
> Verify two dependencies

- OpenOversight/app/templates/incident_detail.html
- OpenOversight/app/templates/incident_list.html
- OpenOversight/app/templates/officer.html
- OpenOversight/app/templates/partials/incident_fields.html
- requirements.txt
- Improve the layout of the incident formatting a little bit, specifically
- Make the tables in the incident list vertically aligned
- Do not display a "None" street in the address, instead omit if any street field is NULL (including only showing the city, if no street was added at all)
- Do not show a "time" field if no time was provided
- If the incident has no report number label it with our internal id (this doesn't seem super useful, but better than just having a list of incidents all with the headline "Incident" I think
This is just a start, especially allowing markdown for the description makes it hard to look acceptable for all different formats. Additional improvements very welcome!
Incident list before:
Incident list after: …
> make some improvements to incident formatting

- OpenOversight/app/auth/forms.py
- OpenOversight/app/auth/views.py
- OpenOversight/tests/test_commands.py
Fixes # 887.
- This PR fixes an issue in which confirmation emails are never sent to users when account approval is enabled for the OO instance. With this fix, when an admin marks a user as "approved", a confirmation email is then sent to the user. I believe this was a regression introduced with PR #873. I'm not sure how to add a unit test for this without actually sending email, otherwise I would add one.
- Added the option for admins to manually confirm users via the profile edit page.
- Fixed a number of CSV import unit tests that were failing because they were expecting user input
> Send account confirmation email to new users when their account gets approved

- .circleci/config.yml
- .github/workflows/main.yml
- requirements.txt
Hopefully fixes issues with the circle ci deploy script. The script fails due to attempting to run docker-compose inside the circle ci docker image which is not supported. Switching back to a "machine" (with a ubuntu version that is still current) will hopefully make the scripts run successfully.
> Switch from docker to "machine" for circle-ci

- .github/workflows/main.yml
- .pre-commit-config.yaml
- CONTRIB.md
- Makefile
- PULL_REQUEST_TEMPLATE.md
- dev-requirements.txt
* This PR adds pre-commit to the project, using pretty much the same config file, as in the orca collective repository.
* Also adds the pre-commit to the github action and changes the tests to run in docker containers instead of hard to test github offered images.
* Finally, also updating the CONTRIB.md and the PR template to mention pre-commit, but a bigger re-write of the documentation should be done once the backport project is complete
> Backport from orca collective - Step 2

- Makefile
- OpenOversight/scripts/entrypoint_prod.sh
- docker-compose.yml
- dockerfiles/web/Dockerfile
- dockerfiles/web/Dockerfile-prod
- Make absolute imports work in prod image
- Absolute imports worked locally, but not in production. Now that we use docker to deploy we can actually fix that by making a small change to the gunicorn start command and the working directory set in the dockerfiles.
- I mirrored the change in the local environment, so hopefully we can catch most problems before staging
- Some changes to the tests makefile were required too
> Support absolute imports in prod image.

- dockerfiles/web/Dockerfile
The debian source "stretch-backports" has been removed. We don't need that backport to use libsqlite3.0 anymore, so we can remove all references to it.
Fixes issues with message `E: The repository 'http://deb.debian.org/debian stretch-backports Release' does not have a Release file.`
> Fix dockerfile by removing outdated source.

- OpenOversight/migrations/env.py
Fixes issue when deploying, see https://github.com/lucyparsons/OpenOversight/actions/runs/5065271720/jobs/9251958094
`TypeError: configure() got multiple values for keyword argument 'compare_type'`
The `compare_type` argument is now directly set to true in the flask-migrate default configuration. Removing the line where we set it will fix this issue, as I verified locally.
> Fix issue with new version of Flask-Migrate.

- .github/workflows/test_prs.yml
https://github.com/lucyparsons/OpenOversight/issues/929
Add `v3.10.x` to the list of versions to build with.
> Build with Python 🐍 `v3.10.x`

- OpenOversight/app/templates/auth/change_password.html
https://github.com/lucyparsons/OpenOversight/issues/948
The old copy just said `Password` for the `New Password` field, which was vague and slightly confusing. I updated that so it was clear what was being asked.
> Address `Change Password` copy

- .github/workflows/build_deploy.yml
- .github/workflows/test_coverage.yml
- .github/workflows/test_prs.yml
- .gitignore
- mypy.ini
https://github.com/lucyparsons/OpenOversight/issues/960
Move to the latest version of Python, specificaly `v3.11.x`.
- @abandoned-prototype needs to mark the `3.11` build as mandatory and remove the designations for `3.8` and `3.9`.
> Move to the latest version of 🐍

- OpenOversight/app/__init__.py
- OpenOversight/app/email_client.py
https://github.com/lucyparsons/OpenOversight/actions/runs/5510368096/jobs/10044531971
For the config to be properly accessed in the `email_client`, a `with app.context:` line needed to be added or the config needed to be added as a parameter to the `EmailClient`.
This should fix the issue.
- Validated fix by creating a new user on my local development environment.
> Add `context` as parameter to `EmailClient`

- CONTRIB.md
- Makefile
- OpenOversight/app/models/config.py
- docker-compose.prod-img.yml
- docker-compose.yml
- requirements.txt
I removed the use of the `FLASK_ENV` variable in the application and replaced it with the `ENV` variable. This was done to remove the warning that you'll see below and to simply the potential updating of Flask to a version higher than `v2.3`.
```console
'FLASK_ENV' is deprecated and will not be used in Flask 2.3. Use 'FLASK_DEBUG' instead.
```
<details><summary>Console Log Output Before Change</summary>
```console
2023-07-11 15:42:33 openoversight-postgres-1  | 
2023-07-11 15:42:33 openoversight-postgres-1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
2023-07-11 15:42:33 openoversight-postgres-1  | 
2023-07-11 15:42:33 openoversight-postgres-1  | 2023-07-11 20:42:33.064 UTC [1] LOG:  starting PostgreSQL 15.3 (Debian 15.3-1.pgdg120+1) on …
```
> Address `FLASK_ENV` warning

- OpenOversight/app/static/css/openoversight.css
- OpenOversight/app/templates/partials/officer_faces.html
- OpenOversight/app/templates/tag.html
https://github.com/lucyparsons/OpenOversight/issues/931
I centered and addressed sizing issues with the officer profile pictures in the profile page, officer list page, and officer image page.
Located in the comments.
> Center and size officer profile pictures

- package.json
https://github.com/lucyparsons/OpenOversight/issues/985
This addition was made so that the below text does not pop up when running the application.
```console
2023-07-21 15:45:07 openoversight-web-1       | warning package.json: No license field
```
> Add license to `package.json`

- OpenOversight/tests/routes/route_helpers.py
- OpenOversight/tests/routes/test_other.py
https://github.com/lucyparsons/OpenOversight/issues/323
Added test to cover an empty string timezone being passed.
> Add additional `/timezone` test

- OpenOversight/app/main/views.py
- OpenOversight/app/models/database.py
- OpenOversight/app/templates/browse.html
- OpenOversight/app/utils/constants.py
- OpenOversight/tests/test_models.py
- requirements.txt
https://github.com/lucyparsons/OpenOversight/issues/797
Added sorting by `state` and `name` columns for department listing , added baseline `Department` statistics for each department, and added cacheing for those `Department` statistics.
Before change:
After change:
> Sort `Department`s and add stats and cacheing

- OpenOversight/app/__init__.py
- OpenOversight/app/utils/constants.py
- requirements.txt
https://github.com/lucyparsons/OpenOversight/issues/996
Added gzip compression to HTML, JS, and CSS file responses via the [`Flask-Compress` package](https://github.com/colour-science/flask-compress).
Network tab of `http://localhost:3000/department/1` without compression:
Network tab of `http://localhost:3000/department/1` with compression:
> Add gzip compression for HTML, JS, and CSS files

- OpenOversight/app/main/views.py
Merging fix https://github.com/OrcaCollective/OpenOversight/pull/347 upstream.
**Original PR description**:
Only add new officers to incidents.
When a user edits an incident currently, we retrieve the Incident from the database and append all officers in the form to that Incident. This led to sqlalchemy trying to insert duplicate rows into the officer_incidents association table.
As far as I can tell, this was silently ignored by sqlalchemy in the past and no unexpected rows were created. With the upgrade to sqlalchemy 2.0.19 (https://github.com/OrcaCollective/OpenOversight/pull/344), the library appears to have started raising exceptions related to this behavior.
This change checks to see whether an officer already exists in Incident.officers before adding them so as to not add duplicate …
> Fix adding duplicate officers to incidents

- OpenOversight/migrations/versions/2023-08-01-1905_b38c133bed3c_add_created_by_and_created_at_columns.py
https://github.com/lucyparsons/OpenOversight/issues/1005
This fixes the issue we were having with trying to drop the `faces_user_id_fkey` in the push to `main`.  What happened was the `faces_user_id_fkey` wasn't saved under a name in the previous database model. PosgreSQL will drop any attached constraints when a column is dropped (presuming there are no `CASCADE` effects), so I am removing the `drop_constraint` commands and JUST dropping the column. This will allow PostgreSQL to take care of the constraint problem for us.
<details><summary>DB migration output</summary>
```console
:/usr/src/app$ flask db upgrade
[2023-08-03 21:48:37,989] INFO in __init__: OpenOversight startup
...
INFO  [sqlalchemy.engine.Engine] COMMIT
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO …
```
> Hotfix: Address missing constraint issue

- OpenOversight/app/main/downloads.py
- OpenOversight/app/main/views.py
- OpenOversight/app/models/database.py
- OpenOversight/app/utils/forms.py
- OpenOversight/tests/conftest.py
- OpenOversight/tests/routes/route_helpers.py
- OpenOversight/tests/test_commands.py
- OpenOversight/tests/test_models.py
- OpenOversight/tests/test_utils.py
Addressed DB warnings that we'd see during creation and removed redundant/unnecessary Model properties.
```console
SAWarning: relationship 'Face.users' will copy column users.id to column faces.user_id, which conflicts with relationship(s): 'Face.user' (copies users.id to faces.user_id), 'User.faces' (copies users.id to faces.user_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="faces,user"' to the 'Face.users' relationship. …
```
> Address database creation warnings

- Makefile
- OpenOversight/app/main/forms.py
- OpenOversight/app/main/views.py
- OpenOversight/app/models/database.py
- OpenOversight/app/templates/browse.html
- OpenOversight/app/templates/input_find_officer.html
- OpenOversight/app/templates/list_officer.html
- OpenOversight/app/templates/partials/officer_general_information.html
- OpenOversight/app/templates/submit_image.html
- OpenOversight/app/utils/db.py
- OpenOversight/tests/conftest.py
- OpenOversight/tests/test_commands.py
- OpenOversight/tests/test_functional.py
Added a `display_name` property to the `Department` model which adds the state to all displays of the department name and sorted all department lists by state and department name.
> Order department listings and add `display_name`

- OpenOversight/app/main/downloads.py
- OpenOversight/app/main/model_view.py
- OpenOversight/app/main/views.py
- OpenOversight/app/models/database.py
- OpenOversight/app/templates/image.html
- OpenOversight/app/templates/partials/officer_descriptions.html
- OpenOversight/app/templates/partials/officer_notes.html
- OpenOversight/app/templates/tag.html
- OpenOversight/app/utils/constants.py
- OpenOversight/app/utils/db.py
- OpenOversight/app/utils/forms.py
- OpenOversight/migrations/versions/2023-08-21-0300_a35aa1a114fa_add_create_and_last_update_columns.py
- OpenOversight/tests/conftest.py
- OpenOversight/tests/routes/test_descriptions.py
- OpenOversight/tests/routes/test_notes.py
#1008 
Add creation and last update columns to track when and by whom models were updated.
Run alembic migration
N/A
> Add create and last_update columns to models

- OpenOversight/app/models/database.py
- OpenOversight/migrations/versions/2023-07-24-1619_52d3f6a21dd9_add__uuid_column_to_users.py
Fixes #1038 
Update `down_revision` since 2 migrations are using `b38c133bed3c` as their `down_revision`.
None!
N/A
> Fix migration down_revision

- OpenOversight/migrations/versions/2023-07-24-1619_52d3f6a21dd9_add__uuid_column_to_users.py
We are currently seeing an error in the deployment process due to the lack of the `gen_random_uuid()` function in the PostgreSQL instance.
```zsh
INFO  [alembic.runtime.migration] Running upgrade a35aa1a114fa -> 52d3f6a21dd9, add _uuid column to users
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
self.dialect.do_execute(
File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
cursor.execute(statement, parameters)
psycopg2.errors.UndefinedFunction: function gen_random_uuid() does not exist
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```
> Address PostgreSQL error

- OpenOversight/migrations/versions/2023-07-24-1619_52d3f6a21dd9_add__uuid_column_to_users.py
The previous build ran into a problem where we added a middleware creation for the `_uuid` column in the `users` table, but did not deal with the problem of the rows that lacked UUIDs in the `users` table. This was dealt with through the use of a loop in the migration that adds a UUID to all pre-existing rows via Python 🐍.
```zsh
% git checkout address_missing_uuids
% make clean_all                          
rm -rf ./OpenOversight/app/static/dist/
docker-compose stop
...
% git checkout 872a01ab  # Checks out a previous version of the branch before we merged in the UUIDs
...
HEAD is now at 872a01ab Remove `HiddenField`s and add `created_by` to `LicensePlate` and `Location` (#1034)
% make start    
docker-compose build
...
% make dev # Create tables and the application at the point in time …
```
> Address missing UUIDs in pre-existing users

- .flake8
- .pre-commit-config.yaml
- dockerfiles/web/Dockerfile
Moved configurations from `.flake8` file to `.pre-commit-config.yaml` and deleted `.flake8`.
> Move flake8 configs to pre-commit

- OpenOversight/app/models/database.py
- OpenOversight/app/static/css/openoversight.css
- OpenOversight/app/templates/partials/officer_faces.html
- OpenOversight/tests/test_models.py
https://github.com/lucyparsons/OpenOversight/issues/1045
Added image carousel for officers with multiple images and additional test coverage.
Multiple images:
Single image:
No images:
> Add image carousel for officers with multiple images

- OpenOversight/app/main/views.py
- OpenOversight/tests/routes/test_image_tagging.py
- OpenOversight/tests/routes/test_officer_and_department.py
I removed the created_by field from the from on editing a `Department`.
> Address edit `Department` error
