OpenOversight/app/static/theme.css, OpenOversight/app/templates/base.html, OpenOversight/app/templates/gallery.html, OpenOversight/app/templates/index.html
=> Add beta banner, request for data corrections

OpenOversight/app/templates/about.html
Per our Press person we should add the Press Release to OO. I have cut it down to the essentials and merged them into one page.
=> add PR to about, fix 404 URL from CPD webpage

DEPLOY.md
Update with notes about how we had to fix prod deployment on the fly for release.
=> Notes about running in production

OpenOversight/app/utils.py, OpenOversight/app/views.py
This significantly increases the speed of getting images for officers from the database - should help a lot with the load from today
=> Big database speedup

OpenOversight/app/forms.py
The reference picture and the form order are reversed. This sorts them the same way
=> Match form rank order to reference picture

OpenOversight/app/utils.py, OpenOversight/test_data.py
Fix for bug found by @r4v5 using our swanky new staging server!
=> Fix for case sensitive query

CONTRIB.md, OpenOversight/test_data.py, OpenOversight/tests/test_utils.py, requirements.txt
This PR adds automatic generation of test data: 120 officers are inserted into the development database with a randomly selected Springfield Police Department officer image. Closes #102.
=> Generate test officers for development environment

OpenOversight/app/templates/complaint.html
=> remove css inheritance

test_data.py
Add in right path to `cop5.jpg`, commit tables in order (`officer.id` in tags were not being set properly), minor style fixes
=> Cleanup test officers

OpenOversight/app/config.py
Discovered during testing of #129 that we should increase the number of test officers to be more realistic in the development VM
=> More realistic number of officers

DEPLOY.md
=> document fabric commands

OpenOversight/app/static/theme.css, OpenOversight/app/templates/gallery.html
OK another attempt at fixing #98! Try this one @freddymartinez9. I ended up rewriting this template because it was a mess, and in the process learned that [bootlint](https://github.com/twbs/bootlint) - an HTML linter for Bootstrap projects - was a thing! (Probably I should do this for the other templates but not a super high priority atm). I tested this in Safari and Chrome and on mobile using [Chrome's Device Mode](https://developers.google.com/web/tools/chrome-devtools/device-mode/).
=> Rewrite gallery template and modify CSS of thumbnail images

OpenOversight/tests/test_models.py, OpenOversight/tests/test_routes.py
Adds a few unit tests for the new auth blueprint
=> Add unit tests for authentication routes

fabfile.py
Refactor this a bit and move some things around, add a confirmation
step before actually doing the deploy. Still not DRY yet, but
the addition of the confirmation step and pip install were the main
priorities here.
=> Make fabfile run pip install before restarting nginx

OpenOversight/tests/test_routes.py
This PR adds a few more unit tests for the auth blueprint functionality
=> Add more unit tests for authentication routes

OpenOversight/tests/conftest.py, OpenOversight/tests/test_models.py, OpenOversight/tests/test_routes.py
We needed that green coveralls badge
=> Add bunch of unit tests to get test coverage up to 90%

.gitignore, OpenOversight/db_backup.py, fabfile.py
requires setting a static URI for the DBs but I am fine having those locally until we can get them from the `.env`, which I am much less familiar with.
=> one line backup of PG DB

fabfile.py
Python list syntax will be the end of me.
=> Fix deploy step of fabfile

DEPLOY.md
Also mention a max file size setting that we'll need to set if we want to accept files larger than ~2M.
=> Update deploy docs to mention S3 access requirements

.travis.yml
I have no idea why it's running our tests twice or freaking out, as the case may be.
=> Update travis to use Ubuntu Trusty docker image

DEPLOY.md
Pictures is big sometimes.
Fixes #190.
=> Update the max request size in nginx configuration

.flake8, .travis.yml, CONTRIB.md, OpenOversight/app/__init__.py, OpenOversight/app/auth/__init__.py, OpenOversight/app/auth/forms.py, OpenOversight/app/config.py, OpenOversight/app/main/__init__.py, OpenOversight/app/main/forms.py, OpenOversight/app/main/views.py, OpenOversight/app/models.py, OpenOversight/app/utils.py, OpenOversight/manage.py, OpenOversight/tests/conftest.py, OpenOversight/tests/test_functional.py, OpenOversight/tests/test_models.py, OpenOversight/tests/test_routes.py, OpenOversight/tests/test_utils.py, create_db.py, dev-requirements.txt, etl/chicago/assignments.py, etl/chicago/invisinst.py, etl/chicago/roster.py, fabfile.py, flickrscraper/flickrgroup.py, flickrscraper/resize.and.detect.py, setup.py, socmint/grab_socmint.py, test_data.py
[Flake8](https://pypi.python.org/pypi/flake8) is a tool that incorporates linting via pyflakes and style checks via PEP8. This PR adds these flake8 checks to CI and modifies the existing Python code (except the committed schema/data migrations) to be flake8 compliant.
=> Add flake8 automated linting and style checking to CI

DEPLOY.md
Updates docs to mention the CORS policy needed
Fixes #209.
- Docs
[n/a] pytests pass in the development environment on my local machine
[n/a] `flake8` checks pass
=> Document the need to create a CORS policy in S3

OpenOversight/app/main/views.py
Some of the officer profile links aren't working on the staging server - but they are in the local dev environment. Yay for staging servers 😉  ❤️.  I get an internal server error. This PR adds logging so that we can hopefully figure out what is going on.
=> Add logging for officer profiles

fabfile.py
Address #118 
[N/A]
[X] I have rebased my changes on current `develop`
[X] pytests pass in the development environment on my local machine
[X] `flake8` checks pass
=> backing up S3 to local app server

README.md
Fixes # .
- New more succinct legal notice
- 
- 
=> Update README.md to alter legal notice for OpenOversight

README.md
=> Update README.md (#249)

OpenOversight/app/templates/leaderboard.html
Closes #232.
- Improve design of leaderboard to look less terrible
=> Improve leaderboard

OpenOversight/app/templates/submit.html
Fixed typo
- Added missing comma (`,`) related to the Dropzone/file uploading
=> submit.html: Fixed JS typo (missing comma)

OpenOversight/app/static/js/jquery.hotkeys.js, OpenOversight/app/templates/base.html, OpenOversight/app/templates/sort.html
Implemented change recommended by @redshiftzero at https://github.com/lucyparsons/OpenOversight/pull/267
- Underline first letter of No/Skip/Yes buttons to signal hotkeys
=> [Cleaner] Classify cops quickly with hotkeys :-D

vagrant/puppet/manifests/default.pp
Fixes #255, vagrant provisioning with wrong permissions
- N/A
None
[ Y ] I have rebased my changes on current `develop`
[N/A ] pytests pass in the development environment on my local machine
[ N/A ] `flake8` checks pass
=> fix file permissions

OpenOversight/app/templates/leaderboard.html
Brings leaderboard fix into develop, this fix is now in prod (thanks @freddymartinez9)
=> Merge leaderboard hotfix back into develop

OpenOversight/app/main/views.py
Hat tip to @bmintz for the find.
none
=> Fix octal representation of this umask

OpenOversight/app/templates/about.html
Fixes #314. 
- Adds text written by @magpiewings
nothin fancy here
=> Make copy on about page less city specific

fabfile.py
Fixes # 302.
-  Add logic to git pull for users who run `fab staging migrate` before trying to deploy. 
[X ] I have rebased my changes on current `develop`
[ N/A] pytests pass in the development environment on my local machine
[ N/A] `flake8` checks pass
=> checkout latest code before attempting migration

OpenOversight/app/static/css/openoversight.css, OpenOversight/app/templates/about.html, OpenOversight/app/templates/privacy.html
Works on #322, #252. Fixes #336.
- fix nav bar shifting on hover
- fixes warrant canary broken link
- basic styling on privacy page
=> privacy styling

README.md
I decided to keep this simple and just have the amount be S, M, L for simplicity since everything marked tip is marked that way because it's an important issue to implement.
=> Explain that we will provide tips / $$$ for contributions

OpenOversight/app/config.py
=> Bump Flask max request size to 50MB to allow for high res uploads #notip

OpenOversight/app/__init__.py
=> Flask-Limiter: change global_limits to default_limits

CONTRIB.md
Fixes #389 
For those unfamiliar with Vagrant/VirtualBox or Python, add some more details to instructions to make it easier to set up your dev environment and get up and running.
^--there appear to be `flake8` failures in other files? D:
=> Add details to contribution instructions.

CONTRIB.md
Some people were confused that the photo upload doesn't work, so this PR is just documenting somewhere that it isn't working
=> Document the development env deficiencies

OpenOversight/app/main/views.py, OpenOversight/tests/test_routes.py
Fixes #289.
fixes handling of invalid ids
=> identification: fix handling of invalid ids

docker-compose.yml
Allows specifying s3 settings for development envs.
=> docker-compose.yml: add Docker env vars

OpenOversight/app/templates/submit_department.html
Fixes #374.
- Adds detail about what pictures should be submitted and how to mitigate privacy concerns 
=> Makes submission page clearer

OpenOversight/app/templates/submit_department.html
Fixes #386.
- Explainer of what happens after photos are submitted
- Step by step instructions for submitting pictures on desktop vs mobile 
=> Adds more instructions for photo submissions

OpenOversight/app/static/css/openoversight.css, OpenOversight/app/templates/label_data.html
Fixes #383
- Move tutorial
- Add colors
Style fixing with @Kimerie  🎉
=> move tutorial, make it scream out to users

OpenOversight/app/templates/input_find_ooid.html
Fixes #409 .
- makes clear which field in roster search is for badge number and which is for last name
asap lol
=> fix lil roster bug

OpenOversight/app/models.py
Fixes #426 
-  Update date-time to date in officer detail
=> Update datetime to date in officer detail

OpenOversight/app/models.py
Reverts lucyparsons/OpenOversight#429
Let's merge changes like #429 only with the corresponding migration (and let's make sure we test the migration with data in that columns in question in the database :wink:). Thankfully this contributor (:heart:!) has prepared a new PR - #431 - with the migration. Once review and testing over there looks good _then_ we can bring in the change.
=> Revert "Update datetime to date in officer detail"

OpenOversight/app/main/views.py, OpenOversight/app/templates/cop_face.html, OpenOversight/tests/conftest.py, OpenOversight/tests/test_routes.py
Help! I created a beautiful beautiful test, and I'm getting the following encoding error:
`UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2828: ordinal not in range(128)` when I run it. Has anyone run into this before?
Fixes #415 .
I think we should consider changing the way these views work - it seems strange that marking the tag as complete is done in a different place from creating the tag.
- Modifies the complete_tagging view to pass department along
- Modifies tagging templates to show department name
=> 415 incorrect department

OpenOversight/app/main/forms.py, OpenOversight/app/templates/about.html, OpenOversight/app/templates/index.html, OpenOversight/app/templates/input_find_officer.html, OpenOversight/app/templates/label_data.html, OpenOversight/app/templates/sort.html, OpenOversight/app/templates/submit_department.html, OpenOversight/app/templates/tutorial.html, OpenOversight/tests/routes/test_image_tagging.py, README.md
Fixes #464
- Change language where needed from "police" to "law enforcement agency" and from "police officer" to "law enforcement officer"
=> Replace "police department" with "law enforcement agency"

OpenOversight/app/templates/about.html, OpenOversight/app/templates/index.html
Ready for review, just some long needed changes on about and home pages
=> Updates index and about page text

CONTRIB.md
Fixes #437 .
- Update CONTRIB.md
=> Update Contrib documentation of create database command

OpenOversight/app/main/views.py, OpenOversight/app/templates/officer.html
Fixes #511
- This enables an AC or admin to see which image the tag is from,
and which user tagged it.
Nothing major
=> Make each photo a link to the tag on the profile

requirements.txt
- There's a DoS vulnerability in the version of Flask we are using ([CVE-2018-1000656](https://nvd.nist.gov/vuln/detail/CVE-2018-1000656)), this updates to latest
- Good to merge pending green CI
=> CVE-2018-1000656: Update Flask to 1.0.2

requirements.txt
Static assets were failing to load on staging without this. I'm not quite sure why the raw gunicorn in dev worked.
```
Aug 25 03:03:47 staging.openoversight.lucyparsonslabs.com gunicorn[11186]: [2018-08-25 03:03:47 +0000] [11192] [ERROR] Error handling request /static/js/bootstrap.min.js
Aug 25 03:03:47 staging.openoversight.lucyparsonslabs.com gunicorn[11186]: Traceback (most recent call last):
Aug 25 03:03:47 staging.openoversight.lucyparsonslabs.com gunicorn[11186]:   File "/home/nginx/oovirtenv/venv/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 135, in handle
Aug 25 03:03:47 staging.openoversight.lucyparsonslabs.com gunicorn[11186]:     self.handle_request(listener, req, client, addr)
Aug 25 03:03:47 staging.openoversight.lucyparsonslabs.com gunicorn[11186]:   File …
```
=> Upgrade werkzeug to 0.14+ for flask 1.x compatibility

OpenOversight/app/static/css/bootstrap.css
Fixes #495.
- Adds a line to body in bootstrap css
=> Fix side to side scroll

OpenOversight/app/templates/about.html
Fixes ##588.
- Update about page with NYC and anticipated Baltimore info
- Removes ICE and CBP info after discussion with @redshiftzero
=> Update about page

OpenOversight/app/templates/incident_list.html
Hello! This is my first issue, just trying to get my dev environment set up and this seemed like low-hanging fruit. Appreciate any pointers if I missed anything important. 
Fixes #587.
=> Remove all incidents link - Closes #587

CONTRIB.md
=> Add bulk-add-officer command to documentation

CONTRIB.md
Fixes #644  .
- Include instructions about using virtualenv with the project. 
I didn't run pytests since I only touched documentation.
=> include instructions about virtualenv

.travis.yml
- Adding additional python 3 jobs so we shake out issues on different versions
=> [ci] add additional python 3.x jobs

OpenOversight/migrations/versions/bde5faf0270c_add_uii_to_departments.py
Reposition the uii string migration to be logically after the uiil
migration so that time becomes a straight line and migrations work in
staging again.
I'm not actually sure this is the resolution we want; tagging @McEileen to review.
before:
```
www-data@ae0d4b1bd469:/usr/src/app/OpenOversight$ flask db history
[2019-05-07 04:21:41,285] INFO in __init__: OpenOversight startup
[2019-05-07 04:21:41,405] INFO in __init__: OpenOversight startup
2a9064a2507c -> bde5faf0270c (head), add uii string column to departments table
3015d1dd9eb4 -> 8ce3de7679c2 (head), adds unique_internal_identifier_label to departments table
c1fc26073f85 -> 3015d1dd9eb4, Add Jobs table
770ed51b4e16 -> c1fc26073f85, Rank rename PO -> POLICE OFFICER
2a9064a2507c -> 770ed51b4e16, Add salaries table
5c5b80cab45e -> …
```
=> Fix migration tree to be a line

dev-requirements.txt, requirements.txt
Ready for review .
Fixes #679.
- Update the `Pillow` version to be compatible with Python 3
- Update the `pytest` version to remove errors from `make test` that @ssempervirens saw in #691 
n/a
n/a
=> update Pillow version in requirements.txt

DEPLOY.md, OpenOversight/app/auth/forms.py, OpenOversight/app/config.py, OpenOversight/app/main/forms.py, OpenOversight/app/main/model_view.py, OpenOversight/app/utils.py, OpenOversight/tests/conftest.py, dockerfiles/web/Dockerfile, requirements.txt
This PR updates some and pins all remaining requirements. I went through and handled the most annoying Deprecation warnings. The others we can create issues for.  
`psycopg2` build dependencies have been installed on staging and production. 
Despite Travis' lack of status below, tests are passing: https://travis-ci.org/github/lucyparsons/OpenOversight/builds/700259808
=> update and pin remaining production requirements

OpenOversight/app/main/views.py, OpenOversight/tests/routes/test_officer_and_department.py
Fixes #778  .
Small PR to fix the download of assignments to actually restrict to the given department & fixing the test
Also only offering departments with officers on the `/download/all` page
=> fixing #778 - assignment downloads

OpenOversight/app/templates/list_officer.html
Fixes #793 which is causing a 500 in production and staging
This has been applied to staging and production already as a hotfix
=> [deployed as hotfix] bugfix: resolve TypeError when trying to concatenate str with NoneType

Makefile, OpenOversight/app/commands.py, OpenOversight/app/main/model_view.py, OpenOversight/app/model_imports.py, OpenOversight/app/models.py, dev-requirements.txt, dockerfiles/web/Dockerfile, mypy.ini
Ready for review!
This PR (https://github.com/lucyparsons/OpenOversight/pull/830) added mypy type checking as part of the linting for this code-base. It did not however, resolve the original errors said linting surfaced. This PR makes changes to files within `OpenOversight/app` , adding type annotations and therefore resolving those issues.
The changes in  https://github.com/lucyparsons/OpenOversight/pull/830 are also on this branch.
- Add dateparser.parser as a specific import to `model_imports.py` (I think just importing dateparser is a bug?)
- Add type annotations for two Dictionaries in `commands.py` 
- Import and use the DefaultMeta class from flask_sqlalchemy to have types for the db.Model 
- I saw how to do this via …
=> 737B resolve mypy errors

OpenOversight/app/config.py
Enable uploading .webp images.
=> Whitelist .webp for image upload

OpenOversight/app/commands.py, OpenOversight/app/utils.py
Fixes #696 .
- Parse date/datetime fields with dateutil to validate and allow comparison with stored date fields
- Provide default value for assignment titles ("Not Sure") in process_assignments to prevent duplicates in the case of empty/missing titles
=> normalizing dates, setting default assignment

CONTRIB.md, PULL_REQUEST_TEMPLATE.md
Fixes #837 .
- Add instructions on privacy settings 
- Clarify instructions on creating a PR
- Add notice to Pull Request
- `N/A` pytests pass in the development environment on my local machine
- `N/A` `flake8` checks pass
=> update CONTRIB.md and PR template

.circleci/config.yml
Update circleci image to something that's still under development
=> Fix CircleCI automated tasks

.circleci/config.yml
Downgrading the machine used for CircleCI. Also reducing the packages installed.
=> Fix deployment via CircleCI.

OpenOversight/app/__init__.py, OpenOversight/app/custom.py, OpenOversight/app/main/downloads.py, OpenOversight/app/main/views.py, OpenOversight/app/models.py, OpenOversight/app/static/css/openoversight.css, OpenOversight/app/static/scss/bootstrap/_variables.scss, OpenOversight/app/templates/about.html, OpenOversight/app/templates/all_depts.html, OpenOversight/app/templates/base.html, OpenOversight/app/templates/cop_face.html, OpenOversight/app/templates/image.html, OpenOversight/app/templates/index.html, OpenOversight/app/templates/input_find_officer.html, OpenOversight/app/templates/label_data.html, OpenOversight/app/templates/list_officer.html, OpenOversight/app/templates/officer.html, OpenOversight/app/templates/partials/links_and_videos_row.html, OpenOversight/app/templates/partials/officer_add_photos.html, OpenOversight/app/templates/partials/officer_assignment_history.html, OpenOversight/app/templates/partials/officer_descriptions.html, OpenOversight/app/templates/partials/officer_faces.html, OpenOversight/app/templates/partials/officer_general_information.html, OpenOversight/app/templates/partials/officer_incidents.html, OpenOversight/app/templates/partials/officer_notes.html, OpenOversight/app/templates/partials/officer_salary.html, OpenOversight/app/templates/submit_image.html, OpenOversight/app/utils.py, OpenOversight/tests/test_utils.py
Backport from [OrcaCollective fork](https://github.com/OrcaCollective/OpenOversight) up to the big formatting change.
Following is a list of all commits in that range with a comment whether each commit was included.
* 99cdd3e Initial setup and customization (OrcaCollective#1)
* Most changes specific to instance and deployment. Cherry-picked two commits:
* https://github.com/OrcaCollective/OpenOversight/pull/1/commits/e780bbbcba5734e1919396075975e5b4b05935a7 Swap the fields that are shown by default in browse view 
* https://github.com/OrcaCollective/OpenOversight/pull/1/commits/4407840fd08f3c845f5dcc32eba64392ac9b7bf7 Add custom JPEG identification patch 
* 3c7a8eb Image submission: Remove SecureDrop references (OrcaCollective#8)
* Included
* 467d1cc Alternative storage backend for …
=> Backport from orca collective - Step 1

docker-compose.prod-img.yml, dockerfiles/web/Dockerfile
Follow up to #916, in which one scenario was missed and broke the ability to run flask commands.
=> Fix prod yml issue which breaks flask commands.

requirements.txt
Updating various dependencies to latest or recent versions.
Definitely should test this in staging a little bit since not all functionality might be covered by tests.
=> Upgrade more packages.

Makefile, create_db.py
Need comments.
This PR was submitted to address some issues I ran into while using the `make dev` command. I'll leave this up and we can talk about the changes when someone else is around.
=> Update `make dev`-associated commands

.github/workflows/test_prs.yml
https://github.com/lucyparsons/OpenOversight/issues/929
Add `v3.11.x` to the list of versions to build with.
=> Build with Python 🐍 `v3.11.x`

.pre-commit-config.yaml, OpenOversight/app/auth/views.py, OpenOversight/app/commands.py, OpenOversight/app/csv_imports.py, OpenOversight/app/email_client.py, OpenOversight/app/main/model_view.py, OpenOversight/app/main/views.py, OpenOversight/app/models/config.py, OpenOversight/app/models/database.py, OpenOversight/app/models/database_imports.py, OpenOversight/app/utils/cloud.py, OpenOversight/app/utils/constants.py, OpenOversight/app/utils/forms.py, OpenOversight/app/utils/general.py, OpenOversight/app/widgets.py, OpenOversight/tests/routes/route_helpers.py, OpenOversight/tests/routes/test_image_tagging.py, OpenOversight/tests/routes/test_incidents.py, OpenOversight/tests/routes/test_officer_and_department.py, OpenOversight/tests/routes/test_user_api.py, OpenOversight/tests/test_functional.py, db_backup.py, dev-requirements.txt, tasks.py
Ran the `pre-commit autoupdate` command and added the [`flynt`](https://github.com/ikamensh/flynt) package to `pre-commit` to make sure we don't have any `.format()` strings in the repository.
=> Update `pre-commit` packages and add `flynt`

.github/issue_template.md
Add personal identity note to the issue template.
=> Add `New Contributor` note to issue template

OpenOversight/tests/routes/route_helpers.py
https://github.com/lucyparsons/OpenOversight/issues/1010
Added typing to parameters and returns for the `login_` functions.
=> Add typing to `login_` functions

OpenOversight/app/filters.py, OpenOversight/app/main/forms.py, OpenOversight/app/main/model_view.py, OpenOversight/app/main/views.py, OpenOversight/app/templates/partials/incident_fields.html, OpenOversight/app/utils/constants.py, OpenOversight/app/utils/forms.py, OpenOversight/tests/routes/test_descriptions.py, OpenOversight/tests/routes/test_image_tagging.py, OpenOversight/tests/routes/test_incidents.py, OpenOversight/tests/routes/test_notes.py, OpenOversight/tests/routes/test_officer_and_department.py, OpenOversight/tests/routes/test_singular_redirects.py, OpenOversight/tests/test_database_cache.py, OpenOversight/tests/test_models.py
https://github.com/lucyparsons/OpenOversight/issues/1033
Remove `created_by` from `Form` models and add `created_by` to `LicensePlate` and `Location` models.
=> Remove hidden fields and add `created_by` to `LicensePlate` and `Location`
